// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/categories/powertrain.proto

package org.sensoris.categories.powertrain;

public final class SensorisPowertrainCategory {
  private SensorisPowertrainCategory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_powertrain_EngineStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_powertrain_EngineStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_powertrain_TransmissionStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_powertrain_TransmissionStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_powertrain_CruiseControlStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_powertrain_CruiseControlStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_powertrain_PowertrainCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_powertrain_PowertrainCategory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-sensoris/protobuf/categories/powertrai" +
      "n.proto\022\'sensoris.protobuf.categories.po" +
      "wertrain\032\"sensoris/protobuf/types/base.p" +
      "roto\"\231\004\n\014EngineStatus\022=\n\010envelope\030\001 \001(\0132" +
      "+.sensoris.protobuf.types.base.EventEnve" +
      "lope\022]\n\017ignition_status\030\002 \001(\0162D.sensoris" +
      ".protobuf.categories.powertrain.EngineSt" +
      "atus.IgnitionStatus\022a\n\021powertrain_status" +
      "\030\003 \001(\0162F.sensoris.protobuf.categories.po" +
      "wertrain.EngineStatus.PowertrainStatus\"\221" +
      "\001\n\016IgnitionStatus\022\033\n\027UNKNOWN_IGNITION_ST" +
      "ATUS\020\000\022\021\n\rIGNITION_LOCK\020\001\022\020\n\014IGNITION_OF" +
      "F\020\002\022\030\n\024IGNITION_ACCESSORIES\020\003\022\017\n\013IGNITIO" +
      "N_ON\020\004\022\022\n\016IGNITION_START\020\005\"t\n\020Powertrain" +
      "Status\022\035\n\031UNKNOWN_POWERTRAIN_STATUS\020\000\022\022\n" +
      "\016POWERTRAIN_OFF\020\001\022\027\n\023POWERTRAIN_ECO_MODE" +
      "\020\002\022\024\n\020POWERTRAIN_READY\020\003\"\374\003\n\022Transmissio" +
      "nStatus\022=\n\010envelope\030\001 \001(\0132+.sensoris.pro" +
      "tobuf.types.base.EventEnvelope\022W\n\tgear_m" +
      "ode\030\002 \001(\0162D.sensoris.protobuf.categories" +
      ".powertrain.TransmissionStatus.GearMode\022" +
      "Y\n\ndrive_mode\030\003 \001(\0162E.sensoris.protobuf." +
      "categories.powertrain.TransmissionStatus" +
      ".DriveMode\022>\n\014current_gear\030\004 \001(\0132(.senso" +
      "ris.protobuf.types.base.Int64Value\"\\\n\010Ge" +
      "arMode\022\025\n\021UNKNOWN_GEAR_MODE\020\000\022\t\n\005DRIVE\020\001" +
      "\022\n\n\006MANUAL\020\002\022\013\n\007REVERSE\020\003\022\010\n\004PARK\020\004\022\013\n\007N" +
      "EUTRAL\020\005\"U\n\tDriveMode\022\026\n\022UNKNOWN_DRIVE_M" +
      "ODE\020\000\022\007\n\003ECO\020\001\022\013\n\007COMFORT\020\002\022\t\n\005SPORT\020\003\022\017" +
      "\n\013SUPER_SPORT\020\004\"\275\003\n\023CruiseControlStatus\022" +
      "=\n\010envelope\030\001 \001(\0132+.sensoris.protobuf.ty" +
      "pes.base.EventEnvelope\022O\n\004type\030\002 \001(\0162A.s" +
      "ensoris.protobuf.categories.powertrain.C" +
      "ruiseControlStatus.Type\022:\n\006status\030\003 \001(\0162" +
      "*.sensoris.protobuf.types.base.SystemSta" +
      "tus\022F\n\016selected_speed\030\004 \001(\0132(.sensoris.p" +
      "rotobuf.types.base.Int64ValueB\004\210\265\030\001\022U\n\035s" +
      "elected_time_to_lead_vehicle\030\005 \001(\0132(.sen" +
      "soris.protobuf.types.base.Int64ValueB\004\210\265" +
      "\030\001\";\n\004Type\022\020\n\014UNKNOWN_TYPE\020\000\022\t\n\005SPEED\020\001\022" +
      "\026\n\022SPEED_AND_DISTANCE\020\002\"\333\002\n\022PowertrainCa" +
      "tegory\022@\n\010envelope\030\001 \001(\0132..sensoris.prot" +
      "obuf.types.base.CategoryEnvelope\022L\n\rengi" +
      "ne_status\030\002 \003(\01325.sensoris.protobuf.cate" +
      "gories.powertrain.EngineStatus\022X\n\023transm" +
      "ission_status\030\003 \003(\0132;.sensoris.protobuf." +
      "categories.powertrain.TransmissionStatus" +
      "\022[\n\025cruise_control_status\030\004 \003(\0132<.sensor" +
      "is.protobuf.categories.powertrain.Cruise" +
      "ControlStatusBE\n\"org.sensoris.categories" +
      ".powertrainB\032SensorisPowertrainCategoryP" +
      "\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.sensoris.types.base.SensorisBaseTypes.getDescriptor(),
        }, assigner);
    internal_static_sensoris_protobuf_categories_powertrain_EngineStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensoris_protobuf_categories_powertrain_EngineStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_powertrain_EngineStatus_descriptor,
        new java.lang.String[] { "Envelope", "IgnitionStatus", "PowertrainStatus", });
    internal_static_sensoris_protobuf_categories_powertrain_TransmissionStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensoris_protobuf_categories_powertrain_TransmissionStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_powertrain_TransmissionStatus_descriptor,
        new java.lang.String[] { "Envelope", "GearMode", "DriveMode", "CurrentGear", });
    internal_static_sensoris_protobuf_categories_powertrain_CruiseControlStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sensoris_protobuf_categories_powertrain_CruiseControlStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_powertrain_CruiseControlStatus_descriptor,
        new java.lang.String[] { "Envelope", "Type", "Status", "SelectedSpeed", "SelectedTimeToLeadVehicle", });
    internal_static_sensoris_protobuf_categories_powertrain_PowertrainCategory_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sensoris_protobuf_categories_powertrain_PowertrainCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_powertrain_PowertrainCategory_descriptor,
        new java.lang.String[] { "Envelope", "EngineStatus", "TransmissionStatus", "CruiseControlStatus", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.sensoris.types.base.SensorisBaseTypes.exponent);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.sensoris.types.base.SensorisBaseTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
