// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/categories/traffic_events.proto

package org.sensoris.categories.trafficevents;

public interface DangerousSlowDownOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensoris.protobuf.categories.trafficevents.DangerousSlowDown)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  boolean hasEnvelope();
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  org.sensoris.types.base.EventEnvelope getEnvelope();
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  org.sensoris.types.base.EventEnvelopeOrBuilder getEnvelopeOrBuilder();

  /**
   * <pre>
   * Speed reduction and accuracy.
   * &#64;unit Meter Per Second
   * &#64;resolution 0.1
   * &#64;range ( , 0)
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy speed_reduction_and_accuracy = 2 [(.sensoris.protobuf.types.base.exponent) = 1];</code>
   */
  boolean hasSpeedReductionAndAccuracy();
  /**
   * <pre>
   * Speed reduction and accuracy.
   * &#64;unit Meter Per Second
   * &#64;resolution 0.1
   * &#64;range ( , 0)
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy speed_reduction_and_accuracy = 2 [(.sensoris.protobuf.types.base.exponent) = 1];</code>
   */
  org.sensoris.types.spatial.XyzVectorAndAccuracy getSpeedReductionAndAccuracy();
  /**
   * <pre>
   * Speed reduction and accuracy.
   * &#64;unit Meter Per Second
   * &#64;resolution 0.1
   * &#64;range ( , 0)
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.XyzVectorAndAccuracy speed_reduction_and_accuracy = 2 [(.sensoris.protobuf.types.base.exponent) = 1];</code>
   */
  org.sensoris.types.spatial.XyzVectorAndAccuracyOrBuilder getSpeedReductionAndAccuracyOrBuilder();

  /**
   * <pre>
   * Time period over which the speed reduction was detected.
   * &#64;unit Second
   * &#64;resolution 1
   * &#64;range (0, )
   * </pre>
   *
   * <code>.google.protobuf.Int64Value time_period = 3 [(.sensoris.protobuf.types.base.exponent) = 0];</code>
   */
  boolean hasTimePeriod();
  /**
   * <pre>
   * Time period over which the speed reduction was detected.
   * &#64;unit Second
   * &#64;resolution 1
   * &#64;range (0, )
   * </pre>
   *
   * <code>.google.protobuf.Int64Value time_period = 3 [(.sensoris.protobuf.types.base.exponent) = 0];</code>
   */
  com.google.protobuf.Int64Value getTimePeriod();
  /**
   * <pre>
   * Time period over which the speed reduction was detected.
   * &#64;unit Second
   * &#64;resolution 1
   * &#64;range (0, )
   * </pre>
   *
   * <code>.google.protobuf.Int64Value time_period = 3 [(.sensoris.protobuf.types.base.exponent) = 0];</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getTimePeriodOrBuilder();
}
