// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/categories/traffic_events.proto

package org.sensoris.categories.trafficevents;

public final class SensorisTrafficEventsCategory {
  private SensorisTrafficEventsCategory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_Hazard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_Hazard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_Hazard_TypeAndConfidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_Hazard_TypeAndConfidence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_DangerousSlowDown_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_DangerousSlowDown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_TypeAndConfidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_TypeAndConfidence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_TypeAndConfidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_TypeAndConfidence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_TypeAndConfidence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_TypeAndConfidence_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficEventsCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensoris_protobuf_categories_trafficevents_TrafficEventsCategory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1sensoris/protobuf/categories/traffic_e" +
      "vents.proto\022*sensoris.protobuf.categorie" +
      "s.trafficevents\032\036google/protobuf/wrapper" +
      "s.proto\032\"sensoris/protobuf/types/base.pr" +
      "oto\032%sensoris/protobuf/types/spatial.pro" +
      "to\"\332\005\n\006Hazard\022=\n\010envelope\030\001 \001(\0132+.sensor" +
      "is.protobuf.types.base.EventEnvelope\022L\n\020" +
      "detection_status\030\002 \001(\01322.sensoris.protob" +
      "uf.types.base.EventDetectionStatus\022a\n\023ty" +
      "pe_and_confidence\030\003 \001(\0132D.sensoris.proto" +
      "buf.categories.trafficevents.Hazard.Type" +
      "AndConfidence\022O\n\tdirection\030\004 \001(\0162<.senso" +
      "ris.protobuf.categories.trafficevents.Ha" +
      "zard.Direction\032\265\002\n\021TypeAndConfidence\022W\n\004" +
      "type\030\001 \001(\0162I.sensoris.protobuf.categorie" +
      "s.trafficevents.Hazard.TypeAndConfidence" +
      ".Type\022<\n\nconfidence\030\002 \001(\0132(.sensoris.pro" +
      "tobuf.types.base.Confidence\"\210\001\n\004Type\022\020\n\014" +
      "UNKNOWN_TYPE\020\000\022\017\n\013OBSTRUCTION\020\001\022\014\n\010ACCID" +
      "ENT\020\002\022\027\n\023BROKEN_DOWN_VEHICLE\020\003\022\020\n\014SLOW_V" +
      "EHICLE\020\004\022\025\n\021WRONG_WAY_VEHICLE\020\005\022\r\n\tROADW" +
      "ORKS\020\006\"W\n\tDirection\022\025\n\021UNKNOWN_DIRECTION" +
      "\020\000\022\021\n\rEGO_DIRECTION\020\001\022\026\n\022OPPOSITE_DIRECT" +
      "ION\020\002\022\010\n\004BOTH\020\003\"\355\001\n\021DangerousSlowDown\022=\n" +
      "\010envelope\030\001 \001(\0132+.sensoris.protobuf.type" +
      "s.base.EventEnvelope\022a\n\034speed_reduction_" +
      "and_accuracy\030\002 \001(\01325.sensoris.protobuf.t" +
      "ypes.spatial.XyzVectorAndAccuracyB\004\210\265\030\001\022" +
      "6\n\013time_period\030\003 \001(\0132\033.google.protobuf.I" +
      "nt64ValueB\004\210\265\030\000\"\236\004\n\020TrafficCondition\022=\n\010" +
      "envelope\030\001 \001(\0132+.sensoris.protobuf.types" +
      ".base.EventEnvelope\022L\n\020detection_status\030" +
      "\002 \001(\01322.sensoris.protobuf.types.base.Eve" +
      "ntDetectionStatus\022k\n\023type_and_confidence" +
      "\030\003 \001(\0132N.sensoris.protobuf.categories.tr" +
      "afficevents.TrafficCondition.TypeAndConf" +
      "idence\032\217\002\n\021TypeAndConfidence\022a\n\004type\030\001 \001" +
      "(\0162S.sensoris.protobuf.categories.traffi" +
      "cevents.TrafficCondition.TypeAndConfiden" +
      "ce.Type\022<\n\nconfidence\030\002 \001(\0132(.sensoris.p" +
      "rotobuf.types.base.Confidence\"Y\n\004Type\022\020\n" +
      "\014UNKNOWN_TYPE\020\000\022\r\n\tFREE_FLOW\020\001\022\t\n\005HEAVY\020" +
      "\002\022\010\n\004SLOW\020\003\022\013\n\007QUEUING\020\004\022\016\n\nSTATIONARY\020\005" +
      "\"\263\004\n\tRoadWorks\022=\n\010envelope\030\001 \001(\0132+.senso" +
      "ris.protobuf.types.base.EventEnvelope\022L\n" +
      "\020detection_status\030\002 \001(\01322.sensoris.proto" +
      "buf.types.base.EventDetectionStatus\022d\n\023t" +
      "ype_and_confidence\030\003 \001(\0132G.sensoris.prot" +
      "obuf.categories.trafficevents.RoadWorks." +
      "TypeAndConfidence\022U\n\033lanes_closed_and_co" +
      "nfidence\030\005 \001(\01320.sensoris.protobuf.types" +
      ".base.CountAndConfidence\032\333\001\n\021TypeAndConf" +
      "idence\022Z\n\004type\030\001 \001(\0162L.sensoris.protobuf" +
      ".categories.trafficevents.RoadWorks.Type" +
      "AndConfidence.Type\022<\n\nconfidence\030\002 \001(\0132(" +
      ".sensoris.protobuf.types.base.Confidence" +
      "\",\n\004Type\022\020\n\014UNKNOWN_TYPE\020\000\022\t\n\005START\020\001\022\007\n" +
      "\003END\020\002\"\221\005\n\024RoadWeatherCondition\022=\n\010envel" +
      "ope\030\001 \001(\0132+.sensoris.protobuf.types.base" +
      ".EventEnvelope\022L\n\020detection_status\030\002 \001(\013" +
      "22.sensoris.protobuf.types.base.EventDet" +
      "ectionStatus\022o\n\023type_and_confidence\030\003 \001(" +
      "\0132R.sensoris.protobuf.categories.traffic" +
      "events.RoadWeatherCondition.TypeAndConfi" +
      "dence\022U\n\022depth_and_accuracy\030\004 \001(\01323.sens" +
      "oris.protobuf.types.base.Int64ValueAndAc" +
      "curacyB\004\210\265\030\000\032\243\002\n\021TypeAndConfidence\022e\n\004ty" +
      "pe\030\001 \001(\0162W.sensoris.protobuf.categories." +
      "trafficevents.RoadWeatherCondition.TypeA" +
      "ndConfidence.Type\022<\n\nconfidence\030\002 \001(\0132(." +
      "sensoris.protobuf.types.base.Confidence\"" +
      "i\n\004Type\022\020\n\014UNKNOWN_TYPE\020\000\022\010\n\004SNOW\020\001\022\007\n\003I" +
      "CE\020\002\022\021\n\rFREEZING_RAIN\020\003\022\t\n\005FROST\020\004\022\020\n\014HY" +
      "DROPLANING\020\005\022\014\n\010FLOODING\020\006\"\376\003\n\025TrafficEv" +
      "entsCategory\022@\n\010envelope\030\001 \001(\0132..sensori" +
      "s.protobuf.types.base.CategoryEnvelope\022B" +
      "\n\006hazard\030\002 \003(\01322.sensoris.protobuf.categ" +
      "ories.trafficevents.Hazard\022Z\n\023dangerous_" +
      "slow_down\030\003 \003(\0132=.sensoris.protobuf.cate" +
      "gories.trafficevents.DangerousSlowDown\022W" +
      "\n\021traffic_condition\030\004 \003(\0132<.sensoris.pro" +
      "tobuf.categories.trafficevents.TrafficCo" +
      "ndition\022H\n\troadworks\030\005 \003(\01325.sensoris.pr" +
      "otobuf.categories.trafficevents.RoadWork" +
      "s\022`\n\026road_weather_condition\030\006 \003(\0132@.sens" +
      "oris.protobuf.categories.trafficevents.R" +
      "oadWeatherConditionBK\n%org.sensoris.cate" +
      "gories.trafficeventsB\035SensorisTrafficEve" +
      "ntsCategoryP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          org.sensoris.types.base.SensorisBaseTypes.getDescriptor(),
          org.sensoris.types.spatial.SensorisSpatialTypes.getDescriptor(),
        }, assigner);
    internal_static_sensoris_protobuf_categories_trafficevents_Hazard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensoris_protobuf_categories_trafficevents_Hazard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_Hazard_descriptor,
        new java.lang.String[] { "Envelope", "DetectionStatus", "TypeAndConfidence", "Direction", });
    internal_static_sensoris_protobuf_categories_trafficevents_Hazard_TypeAndConfidence_descriptor =
      internal_static_sensoris_protobuf_categories_trafficevents_Hazard_descriptor.getNestedTypes().get(0);
    internal_static_sensoris_protobuf_categories_trafficevents_Hazard_TypeAndConfidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_Hazard_TypeAndConfidence_descriptor,
        new java.lang.String[] { "Type", "Confidence", });
    internal_static_sensoris_protobuf_categories_trafficevents_DangerousSlowDown_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensoris_protobuf_categories_trafficevents_DangerousSlowDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_DangerousSlowDown_descriptor,
        new java.lang.String[] { "Envelope", "SpeedReductionAndAccuracy", "TimePeriod", });
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_descriptor,
        new java.lang.String[] { "Envelope", "DetectionStatus", "TypeAndConfidence", });
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_TypeAndConfidence_descriptor =
      internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_descriptor.getNestedTypes().get(0);
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_TypeAndConfidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_TrafficCondition_TypeAndConfidence_descriptor,
        new java.lang.String[] { "Type", "Confidence", });
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_descriptor,
        new java.lang.String[] { "Envelope", "DetectionStatus", "TypeAndConfidence", "LanesClosedAndConfidence", });
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_TypeAndConfidence_descriptor =
      internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_descriptor.getNestedTypes().get(0);
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_TypeAndConfidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_RoadWorks_TypeAndConfidence_descriptor,
        new java.lang.String[] { "Type", "Confidence", });
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_descriptor,
        new java.lang.String[] { "Envelope", "DetectionStatus", "TypeAndConfidence", "DepthAndAccuracy", });
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_TypeAndConfidence_descriptor =
      internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_descriptor.getNestedTypes().get(0);
    internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_TypeAndConfidence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_RoadWeatherCondition_TypeAndConfidence_descriptor,
        new java.lang.String[] { "Type", "Confidence", });
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficEventsCategory_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_sensoris_protobuf_categories_trafficevents_TrafficEventsCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensoris_protobuf_categories_trafficevents_TrafficEventsCategory_descriptor,
        new java.lang.String[] { "Envelope", "Hazard", "DangerousSlowDown", "TrafficCondition", "Roadworks", "RoadWeatherCondition", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.sensoris.types.base.SensorisBaseTypes.exponent);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.WrappersProto.getDescriptor();
    org.sensoris.types.base.SensorisBaseTypes.getDescriptor();
    org.sensoris.types.spatial.SensorisSpatialTypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
