// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/categories/road_attribution.proto

package org.sensoris.categories.roadattribution;

/**
 * <pre>
 * Lane boundary merge or split.
 * &#64;relation 1 sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit DERIVED_FROM 2..* sensoris.protobuf.categories.roadattribution.LaneBoundary
 * </pre>
 *
 * Protobuf type {@code sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit}
 */
public  final class LaneBoundaryMergeSplit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit)
    LaneBoundaryMergeSplitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LaneBoundaryMergeSplit.newBuilder() to construct.
  private LaneBoundaryMergeSplit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LaneBoundaryMergeSplit() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LaneBoundaryMergeSplit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.sensoris.types.base.EventEnvelope.Builder subBuilder = null;
            if (envelope_ != null) {
              subBuilder = envelope_.toBuilder();
            }
            envelope_ = input.readMessage(org.sensoris.types.base.EventEnvelope.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(envelope_);
              envelope_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.sensoris.types.base.Confidence.Builder subBuilder = null;
            if (existenceConfidence_ != null) {
              subBuilder = existenceConfidence_.toBuilder();
            }
            existenceConfidence_ = input.readMessage(org.sensoris.types.base.Confidence.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(existenceConfidence_);
              existenceConfidence_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            org.sensoris.types.base.EventDetectionStatus.Builder subBuilder = null;
            if (detectionStatus_ != null) {
              subBuilder = detectionStatus_.toBuilder();
            }
            detectionStatus_ = input.readMessage(org.sensoris.types.base.EventDetectionStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(detectionStatus_);
              detectionStatus_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder subBuilder = null;
            if (typeAndConfidence_ != null) {
              subBuilder = typeAndConfidence_.toBuilder();
            }
            typeAndConfidence_ = input.readMessage(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(typeAndConfidence_);
              typeAndConfidence_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            org.sensoris.types.spatial.PositionAndAccuracy.Builder subBuilder = null;
            if (positionAndAccuracy_ != null) {
              subBuilder = positionAndAccuracy_.toBuilder();
            }
            positionAndAccuracy_ = input.readMessage(org.sensoris.types.spatial.PositionAndAccuracy.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(positionAndAccuracy_);
              positionAndAccuracy_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.class, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.Builder.class);
  }

  public interface TypeAndConfidenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Type.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * Type.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
     */
    org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type getType();

    /**
     * <pre>
     * Confidence of type.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
     */
    boolean hasConfidence();
    /**
     * <pre>
     * Confidence of type.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
     */
    org.sensoris.types.base.Confidence getConfidence();
    /**
     * <pre>
     * Confidence of type.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
     */
    org.sensoris.types.base.ConfidenceOrBuilder getConfidenceOrBuilder();
  }
  /**
   * <pre>
   * Type and confidence.
   * </pre>
   *
   * Protobuf type {@code sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence}
   */
  public  static final class TypeAndConfidence extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)
      TypeAndConfidenceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TypeAndConfidence.newBuilder() to construct.
    private TypeAndConfidence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TypeAndConfidence() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TypeAndConfidence(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              org.sensoris.types.base.Confidence.Builder subBuilder = null;
              if (confidence_ != null) {
                subBuilder = confidence_.toBuilder();
              }
              confidence_ = input.readMessage(org.sensoris.types.base.Confidence.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(confidence_);
                confidence_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_TypeAndConfidence_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_TypeAndConfidence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.class, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder.class);
    }

    /**
     * <pre>
     * Type.
     * </pre>
     *
     * Protobuf enum {@code sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Unknown.
       * </pre>
       *
       * <code>UNKNOWN_TYPE = 0;</code>
       */
      UNKNOWN_TYPE(0),
      /**
       * <pre>
       * Merge.
       * </pre>
       *
       * <code>MERGE = 1;</code>
       */
      MERGE(1),
      /**
       * <pre>
       * Split.
       * </pre>
       *
       * <code>SPLIT = 2;</code>
       */
      SPLIT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Unknown.
       * </pre>
       *
       * <code>UNKNOWN_TYPE = 0;</code>
       */
      public static final int UNKNOWN_TYPE_VALUE = 0;
      /**
       * <pre>
       * Merge.
       * </pre>
       *
       * <code>MERGE = 1;</code>
       */
      public static final int MERGE_VALUE = 1;
      /**
       * <pre>
       * Split.
       * </pre>
       *
       * <code>SPLIT = 2;</code>
       */
      public static final int SPLIT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_TYPE;
          case 1: return MERGE;
          case 2: return SPLIT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * Type.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Type.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
     */
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type getType() {
      @SuppressWarnings("deprecation")
      org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type result = org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type.valueOf(type_);
      return result == null ? org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type.UNRECOGNIZED : result;
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 2;
    private org.sensoris.types.base.Confidence confidence_;
    /**
     * <pre>
     * Confidence of type.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
     */
    public boolean hasConfidence() {
      return confidence_ != null;
    }
    /**
     * <pre>
     * Confidence of type.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
     */
    public org.sensoris.types.base.Confidence getConfidence() {
      return confidence_ == null ? org.sensoris.types.base.Confidence.getDefaultInstance() : confidence_;
    }
    /**
     * <pre>
     * Confidence of type.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
     */
    public org.sensoris.types.base.ConfidenceOrBuilder getConfidenceOrBuilder() {
      return getConfidence();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type.UNKNOWN_TYPE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (confidence_ != null) {
        output.writeMessage(2, getConfidence());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type.UNKNOWN_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (confidence_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getConfidence());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)) {
        return super.equals(obj);
      }
      org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence other = (org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasConfidence() == other.hasConfidence());
      if (hasConfidence()) {
        result = result && getConfidence()
            .equals(other.getConfidence());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasConfidence()) {
        hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
        hash = (53 * hash) + getConfidence().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * Protobuf type {@code sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_TypeAndConfidence_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_TypeAndConfidence_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.class, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder.class);
      }

      // Construct using org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (confidenceBuilder_ == null) {
          confidence_ = null;
        } else {
          confidence_ = null;
          confidenceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_TypeAndConfidence_descriptor;
      }

      @java.lang.Override
      public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence getDefaultInstanceForType() {
        return org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.getDefaultInstance();
      }

      @java.lang.Override
      public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence build() {
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence buildPartial() {
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence result = new org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence(this);
        result.type_ = type_;
        if (confidenceBuilder_ == null) {
          result.confidence_ = confidence_;
        } else {
          result.confidence_ = confidenceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence) {
          return mergeFrom((org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence other) {
        if (other == org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasConfidence()) {
          mergeConfidence(other.getConfidence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * Type.
       * </pre>
       *
       * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * Type.
       * </pre>
       *
       * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type.
       * </pre>
       *
       * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
       */
      public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type getType() {
        @SuppressWarnings("deprecation")
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type result = org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type.valueOf(type_);
        return result == null ? org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type.
       * </pre>
       *
       * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
       */
      public Builder setType(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type.
       * </pre>
       *
       * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Type type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private org.sensoris.types.base.Confidence confidence_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.sensoris.types.base.Confidence, org.sensoris.types.base.Confidence.Builder, org.sensoris.types.base.ConfidenceOrBuilder> confidenceBuilder_;
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public boolean hasConfidence() {
        return confidenceBuilder_ != null || confidence_ != null;
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public org.sensoris.types.base.Confidence getConfidence() {
        if (confidenceBuilder_ == null) {
          return confidence_ == null ? org.sensoris.types.base.Confidence.getDefaultInstance() : confidence_;
        } else {
          return confidenceBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public Builder setConfidence(org.sensoris.types.base.Confidence value) {
        if (confidenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          confidence_ = value;
          onChanged();
        } else {
          confidenceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public Builder setConfidence(
          org.sensoris.types.base.Confidence.Builder builderForValue) {
        if (confidenceBuilder_ == null) {
          confidence_ = builderForValue.build();
          onChanged();
        } else {
          confidenceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public Builder mergeConfidence(org.sensoris.types.base.Confidence value) {
        if (confidenceBuilder_ == null) {
          if (confidence_ != null) {
            confidence_ =
              org.sensoris.types.base.Confidence.newBuilder(confidence_).mergeFrom(value).buildPartial();
          } else {
            confidence_ = value;
          }
          onChanged();
        } else {
          confidenceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public Builder clearConfidence() {
        if (confidenceBuilder_ == null) {
          confidence_ = null;
          onChanged();
        } else {
          confidence_ = null;
          confidenceBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public org.sensoris.types.base.Confidence.Builder getConfidenceBuilder() {
        
        onChanged();
        return getConfidenceFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      public org.sensoris.types.base.ConfidenceOrBuilder getConfidenceOrBuilder() {
        if (confidenceBuilder_ != null) {
          return confidenceBuilder_.getMessageOrBuilder();
        } else {
          return confidence_ == null ?
              org.sensoris.types.base.Confidence.getDefaultInstance() : confidence_;
        }
      }
      /**
       * <pre>
       * Confidence of type.
       * </pre>
       *
       * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.sensoris.types.base.Confidence, org.sensoris.types.base.Confidence.Builder, org.sensoris.types.base.ConfidenceOrBuilder> 
          getConfidenceFieldBuilder() {
        if (confidenceBuilder_ == null) {
          confidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.sensoris.types.base.Confidence, org.sensoris.types.base.Confidence.Builder, org.sensoris.types.base.ConfidenceOrBuilder>(
                  getConfidence(),
                  getParentForChildren(),
                  isClean());
          confidence_ = null;
        }
        return confidenceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)
    }

    // @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence)
    private static final org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence();
    }

    public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TypeAndConfidence>
        PARSER = new com.google.protobuf.AbstractParser<TypeAndConfidence>() {
      @java.lang.Override
      public TypeAndConfidence parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TypeAndConfidence(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TypeAndConfidence> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TypeAndConfidence> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ENVELOPE_FIELD_NUMBER = 1;
  private org.sensoris.types.base.EventEnvelope envelope_;
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  public boolean hasEnvelope() {
    return envelope_ != null;
  }
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  public org.sensoris.types.base.EventEnvelope getEnvelope() {
    return envelope_ == null ? org.sensoris.types.base.EventEnvelope.getDefaultInstance() : envelope_;
  }
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  public org.sensoris.types.base.EventEnvelopeOrBuilder getEnvelopeOrBuilder() {
    return getEnvelope();
  }

  public static final int EXISTENCE_CONFIDENCE_FIELD_NUMBER = 2;
  private org.sensoris.types.base.Confidence existenceConfidence_;
  /**
   * <pre>
   * Confidence that a lane boundary merge or split has been detected.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
   */
  public boolean hasExistenceConfidence() {
    return existenceConfidence_ != null;
  }
  /**
   * <pre>
   * Confidence that a lane boundary merge or split has been detected.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
   */
  public org.sensoris.types.base.Confidence getExistenceConfidence() {
    return existenceConfidence_ == null ? org.sensoris.types.base.Confidence.getDefaultInstance() : existenceConfidence_;
  }
  /**
   * <pre>
   * Confidence that a lane boundary merge or split has been detected.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
   */
  public org.sensoris.types.base.ConfidenceOrBuilder getExistenceConfidenceOrBuilder() {
    return getExistenceConfidence();
  }

  public static final int DETECTION_STATUS_FIELD_NUMBER = 3;
  private org.sensoris.types.base.EventDetectionStatus detectionStatus_;
  /**
   * <pre>
   * Event detection status.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
   */
  public boolean hasDetectionStatus() {
    return detectionStatus_ != null;
  }
  /**
   * <pre>
   * Event detection status.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
   */
  public org.sensoris.types.base.EventDetectionStatus getDetectionStatus() {
    return detectionStatus_ == null ? org.sensoris.types.base.EventDetectionStatus.getDefaultInstance() : detectionStatus_;
  }
  /**
   * <pre>
   * Event detection status.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
   */
  public org.sensoris.types.base.EventDetectionStatusOrBuilder getDetectionStatusOrBuilder() {
    return getDetectionStatus();
  }

  public static final int TYPE_AND_CONFIDENCE_FIELD_NUMBER = 4;
  private org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence typeAndConfidence_;
  /**
   * <pre>
   * Type and confidence.
   * </pre>
   *
   * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
   */
  public boolean hasTypeAndConfidence() {
    return typeAndConfidence_ != null;
  }
  /**
   * <pre>
   * Type and confidence.
   * </pre>
   *
   * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
   */
  public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence getTypeAndConfidence() {
    return typeAndConfidence_ == null ? org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.getDefaultInstance() : typeAndConfidence_;
  }
  /**
   * <pre>
   * Type and confidence.
   * </pre>
   *
   * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
   */
  public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidenceOrBuilder getTypeAndConfidenceOrBuilder() {
    return getTypeAndConfidence();
  }

  public static final int POSITION_AND_ACCURACY_FIELD_NUMBER = 5;
  private org.sensoris.types.spatial.PositionAndAccuracy positionAndAccuracy_;
  /**
   * <pre>
   * Position and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
   */
  public boolean hasPositionAndAccuracy() {
    return positionAndAccuracy_ != null;
  }
  /**
   * <pre>
   * Position and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
   */
  public org.sensoris.types.spatial.PositionAndAccuracy getPositionAndAccuracy() {
    return positionAndAccuracy_ == null ? org.sensoris.types.spatial.PositionAndAccuracy.getDefaultInstance() : positionAndAccuracy_;
  }
  /**
   * <pre>
   * Position and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
   */
  public org.sensoris.types.spatial.PositionAndAccuracyOrBuilder getPositionAndAccuracyOrBuilder() {
    return getPositionAndAccuracy();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (envelope_ != null) {
      output.writeMessage(1, getEnvelope());
    }
    if (existenceConfidence_ != null) {
      output.writeMessage(2, getExistenceConfidence());
    }
    if (detectionStatus_ != null) {
      output.writeMessage(3, getDetectionStatus());
    }
    if (typeAndConfidence_ != null) {
      output.writeMessage(4, getTypeAndConfidence());
    }
    if (positionAndAccuracy_ != null) {
      output.writeMessage(5, getPositionAndAccuracy());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (envelope_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEnvelope());
    }
    if (existenceConfidence_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getExistenceConfidence());
    }
    if (detectionStatus_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDetectionStatus());
    }
    if (typeAndConfidence_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTypeAndConfidence());
    }
    if (positionAndAccuracy_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPositionAndAccuracy());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit)) {
      return super.equals(obj);
    }
    org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit other = (org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit) obj;

    boolean result = true;
    result = result && (hasEnvelope() == other.hasEnvelope());
    if (hasEnvelope()) {
      result = result && getEnvelope()
          .equals(other.getEnvelope());
    }
    result = result && (hasExistenceConfidence() == other.hasExistenceConfidence());
    if (hasExistenceConfidence()) {
      result = result && getExistenceConfidence()
          .equals(other.getExistenceConfidence());
    }
    result = result && (hasDetectionStatus() == other.hasDetectionStatus());
    if (hasDetectionStatus()) {
      result = result && getDetectionStatus()
          .equals(other.getDetectionStatus());
    }
    result = result && (hasTypeAndConfidence() == other.hasTypeAndConfidence());
    if (hasTypeAndConfidence()) {
      result = result && getTypeAndConfidence()
          .equals(other.getTypeAndConfidence());
    }
    result = result && (hasPositionAndAccuracy() == other.hasPositionAndAccuracy());
    if (hasPositionAndAccuracy()) {
      result = result && getPositionAndAccuracy()
          .equals(other.getPositionAndAccuracy());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEnvelope()) {
      hash = (37 * hash) + ENVELOPE_FIELD_NUMBER;
      hash = (53 * hash) + getEnvelope().hashCode();
    }
    if (hasExistenceConfidence()) {
      hash = (37 * hash) + EXISTENCE_CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + getExistenceConfidence().hashCode();
    }
    if (hasDetectionStatus()) {
      hash = (37 * hash) + DETECTION_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getDetectionStatus().hashCode();
    }
    if (hasTypeAndConfidence()) {
      hash = (37 * hash) + TYPE_AND_CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + getTypeAndConfidence().hashCode();
    }
    if (hasPositionAndAccuracy()) {
      hash = (37 * hash) + POSITION_AND_ACCURACY_FIELD_NUMBER;
      hash = (53 * hash) + getPositionAndAccuracy().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Lane boundary merge or split.
   * &#64;relation 1 sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit DERIVED_FROM 2..* sensoris.protobuf.categories.roadattribution.LaneBoundary
   * </pre>
   *
   * Protobuf type {@code sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit)
      org.sensoris.categories.roadattribution.LaneBoundaryMergeSplitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.class, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.Builder.class);
    }

    // Construct using org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (envelopeBuilder_ == null) {
        envelope_ = null;
      } else {
        envelope_ = null;
        envelopeBuilder_ = null;
      }
      if (existenceConfidenceBuilder_ == null) {
        existenceConfidence_ = null;
      } else {
        existenceConfidence_ = null;
        existenceConfidenceBuilder_ = null;
      }
      if (detectionStatusBuilder_ == null) {
        detectionStatus_ = null;
      } else {
        detectionStatus_ = null;
        detectionStatusBuilder_ = null;
      }
      if (typeAndConfidenceBuilder_ == null) {
        typeAndConfidence_ = null;
      } else {
        typeAndConfidence_ = null;
        typeAndConfidenceBuilder_ = null;
      }
      if (positionAndAccuracyBuilder_ == null) {
        positionAndAccuracy_ = null;
      } else {
        positionAndAccuracy_ = null;
        positionAndAccuracyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.sensoris.categories.roadattribution.SensorisRoadAttributionCategory.internal_static_sensoris_protobuf_categories_roadattribution_LaneBoundaryMergeSplit_descriptor;
    }

    @java.lang.Override
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit getDefaultInstanceForType() {
      return org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.getDefaultInstance();
    }

    @java.lang.Override
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit build() {
      org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit buildPartial() {
      org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit result = new org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit(this);
      if (envelopeBuilder_ == null) {
        result.envelope_ = envelope_;
      } else {
        result.envelope_ = envelopeBuilder_.build();
      }
      if (existenceConfidenceBuilder_ == null) {
        result.existenceConfidence_ = existenceConfidence_;
      } else {
        result.existenceConfidence_ = existenceConfidenceBuilder_.build();
      }
      if (detectionStatusBuilder_ == null) {
        result.detectionStatus_ = detectionStatus_;
      } else {
        result.detectionStatus_ = detectionStatusBuilder_.build();
      }
      if (typeAndConfidenceBuilder_ == null) {
        result.typeAndConfidence_ = typeAndConfidence_;
      } else {
        result.typeAndConfidence_ = typeAndConfidenceBuilder_.build();
      }
      if (positionAndAccuracyBuilder_ == null) {
        result.positionAndAccuracy_ = positionAndAccuracy_;
      } else {
        result.positionAndAccuracy_ = positionAndAccuracyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit) {
        return mergeFrom((org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit other) {
      if (other == org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.getDefaultInstance()) return this;
      if (other.hasEnvelope()) {
        mergeEnvelope(other.getEnvelope());
      }
      if (other.hasExistenceConfidence()) {
        mergeExistenceConfidence(other.getExistenceConfidence());
      }
      if (other.hasDetectionStatus()) {
        mergeDetectionStatus(other.getDetectionStatus());
      }
      if (other.hasTypeAndConfidence()) {
        mergeTypeAndConfidence(other.getTypeAndConfidence());
      }
      if (other.hasPositionAndAccuracy()) {
        mergePositionAndAccuracy(other.getPositionAndAccuracy());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.sensoris.types.base.EventEnvelope envelope_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.EventEnvelope, org.sensoris.types.base.EventEnvelope.Builder, org.sensoris.types.base.EventEnvelopeOrBuilder> envelopeBuilder_;
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public boolean hasEnvelope() {
      return envelopeBuilder_ != null || envelope_ != null;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public org.sensoris.types.base.EventEnvelope getEnvelope() {
      if (envelopeBuilder_ == null) {
        return envelope_ == null ? org.sensoris.types.base.EventEnvelope.getDefaultInstance() : envelope_;
      } else {
        return envelopeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder setEnvelope(org.sensoris.types.base.EventEnvelope value) {
      if (envelopeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        envelope_ = value;
        onChanged();
      } else {
        envelopeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder setEnvelope(
        org.sensoris.types.base.EventEnvelope.Builder builderForValue) {
      if (envelopeBuilder_ == null) {
        envelope_ = builderForValue.build();
        onChanged();
      } else {
        envelopeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder mergeEnvelope(org.sensoris.types.base.EventEnvelope value) {
      if (envelopeBuilder_ == null) {
        if (envelope_ != null) {
          envelope_ =
            org.sensoris.types.base.EventEnvelope.newBuilder(envelope_).mergeFrom(value).buildPartial();
        } else {
          envelope_ = value;
        }
        onChanged();
      } else {
        envelopeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder clearEnvelope() {
      if (envelopeBuilder_ == null) {
        envelope_ = null;
        onChanged();
      } else {
        envelope_ = null;
        envelopeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public org.sensoris.types.base.EventEnvelope.Builder getEnvelopeBuilder() {
      
      onChanged();
      return getEnvelopeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public org.sensoris.types.base.EventEnvelopeOrBuilder getEnvelopeOrBuilder() {
      if (envelopeBuilder_ != null) {
        return envelopeBuilder_.getMessageOrBuilder();
      } else {
        return envelope_ == null ?
            org.sensoris.types.base.EventEnvelope.getDefaultInstance() : envelope_;
      }
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.EventEnvelope, org.sensoris.types.base.EventEnvelope.Builder, org.sensoris.types.base.EventEnvelopeOrBuilder> 
        getEnvelopeFieldBuilder() {
      if (envelopeBuilder_ == null) {
        envelopeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.EventEnvelope, org.sensoris.types.base.EventEnvelope.Builder, org.sensoris.types.base.EventEnvelopeOrBuilder>(
                getEnvelope(),
                getParentForChildren(),
                isClean());
        envelope_ = null;
      }
      return envelopeBuilder_;
    }

    private org.sensoris.types.base.Confidence existenceConfidence_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Confidence, org.sensoris.types.base.Confidence.Builder, org.sensoris.types.base.ConfidenceOrBuilder> existenceConfidenceBuilder_;
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public boolean hasExistenceConfidence() {
      return existenceConfidenceBuilder_ != null || existenceConfidence_ != null;
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public org.sensoris.types.base.Confidence getExistenceConfidence() {
      if (existenceConfidenceBuilder_ == null) {
        return existenceConfidence_ == null ? org.sensoris.types.base.Confidence.getDefaultInstance() : existenceConfidence_;
      } else {
        return existenceConfidenceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public Builder setExistenceConfidence(org.sensoris.types.base.Confidence value) {
      if (existenceConfidenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        existenceConfidence_ = value;
        onChanged();
      } else {
        existenceConfidenceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public Builder setExistenceConfidence(
        org.sensoris.types.base.Confidence.Builder builderForValue) {
      if (existenceConfidenceBuilder_ == null) {
        existenceConfidence_ = builderForValue.build();
        onChanged();
      } else {
        existenceConfidenceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public Builder mergeExistenceConfidence(org.sensoris.types.base.Confidence value) {
      if (existenceConfidenceBuilder_ == null) {
        if (existenceConfidence_ != null) {
          existenceConfidence_ =
            org.sensoris.types.base.Confidence.newBuilder(existenceConfidence_).mergeFrom(value).buildPartial();
        } else {
          existenceConfidence_ = value;
        }
        onChanged();
      } else {
        existenceConfidenceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public Builder clearExistenceConfidence() {
      if (existenceConfidenceBuilder_ == null) {
        existenceConfidence_ = null;
        onChanged();
      } else {
        existenceConfidence_ = null;
        existenceConfidenceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public org.sensoris.types.base.Confidence.Builder getExistenceConfidenceBuilder() {
      
      onChanged();
      return getExistenceConfidenceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    public org.sensoris.types.base.ConfidenceOrBuilder getExistenceConfidenceOrBuilder() {
      if (existenceConfidenceBuilder_ != null) {
        return existenceConfidenceBuilder_.getMessageOrBuilder();
      } else {
        return existenceConfidence_ == null ?
            org.sensoris.types.base.Confidence.getDefaultInstance() : existenceConfidence_;
      }
    }
    /**
     * <pre>
     * Confidence that a lane boundary merge or split has been detected.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Confidence existence_confidence = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Confidence, org.sensoris.types.base.Confidence.Builder, org.sensoris.types.base.ConfidenceOrBuilder> 
        getExistenceConfidenceFieldBuilder() {
      if (existenceConfidenceBuilder_ == null) {
        existenceConfidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.Confidence, org.sensoris.types.base.Confidence.Builder, org.sensoris.types.base.ConfidenceOrBuilder>(
                getExistenceConfidence(),
                getParentForChildren(),
                isClean());
        existenceConfidence_ = null;
      }
      return existenceConfidenceBuilder_;
    }

    private org.sensoris.types.base.EventDetectionStatus detectionStatus_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.EventDetectionStatus, org.sensoris.types.base.EventDetectionStatus.Builder, org.sensoris.types.base.EventDetectionStatusOrBuilder> detectionStatusBuilder_;
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public boolean hasDetectionStatus() {
      return detectionStatusBuilder_ != null || detectionStatus_ != null;
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public org.sensoris.types.base.EventDetectionStatus getDetectionStatus() {
      if (detectionStatusBuilder_ == null) {
        return detectionStatus_ == null ? org.sensoris.types.base.EventDetectionStatus.getDefaultInstance() : detectionStatus_;
      } else {
        return detectionStatusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public Builder setDetectionStatus(org.sensoris.types.base.EventDetectionStatus value) {
      if (detectionStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detectionStatus_ = value;
        onChanged();
      } else {
        detectionStatusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public Builder setDetectionStatus(
        org.sensoris.types.base.EventDetectionStatus.Builder builderForValue) {
      if (detectionStatusBuilder_ == null) {
        detectionStatus_ = builderForValue.build();
        onChanged();
      } else {
        detectionStatusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public Builder mergeDetectionStatus(org.sensoris.types.base.EventDetectionStatus value) {
      if (detectionStatusBuilder_ == null) {
        if (detectionStatus_ != null) {
          detectionStatus_ =
            org.sensoris.types.base.EventDetectionStatus.newBuilder(detectionStatus_).mergeFrom(value).buildPartial();
        } else {
          detectionStatus_ = value;
        }
        onChanged();
      } else {
        detectionStatusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public Builder clearDetectionStatus() {
      if (detectionStatusBuilder_ == null) {
        detectionStatus_ = null;
        onChanged();
      } else {
        detectionStatus_ = null;
        detectionStatusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public org.sensoris.types.base.EventDetectionStatus.Builder getDetectionStatusBuilder() {
      
      onChanged();
      return getDetectionStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    public org.sensoris.types.base.EventDetectionStatusOrBuilder getDetectionStatusOrBuilder() {
      if (detectionStatusBuilder_ != null) {
        return detectionStatusBuilder_.getMessageOrBuilder();
      } else {
        return detectionStatus_ == null ?
            org.sensoris.types.base.EventDetectionStatus.getDefaultInstance() : detectionStatus_;
      }
    }
    /**
     * <pre>
     * Event detection status.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventDetectionStatus detection_status = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.EventDetectionStatus, org.sensoris.types.base.EventDetectionStatus.Builder, org.sensoris.types.base.EventDetectionStatusOrBuilder> 
        getDetectionStatusFieldBuilder() {
      if (detectionStatusBuilder_ == null) {
        detectionStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.EventDetectionStatus, org.sensoris.types.base.EventDetectionStatus.Builder, org.sensoris.types.base.EventDetectionStatusOrBuilder>(
                getDetectionStatus(),
                getParentForChildren(),
                isClean());
        detectionStatus_ = null;
      }
      return detectionStatusBuilder_;
    }

    private org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence typeAndConfidence_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidenceOrBuilder> typeAndConfidenceBuilder_;
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public boolean hasTypeAndConfidence() {
      return typeAndConfidenceBuilder_ != null || typeAndConfidence_ != null;
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence getTypeAndConfidence() {
      if (typeAndConfidenceBuilder_ == null) {
        return typeAndConfidence_ == null ? org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.getDefaultInstance() : typeAndConfidence_;
      } else {
        return typeAndConfidenceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public Builder setTypeAndConfidence(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence value) {
      if (typeAndConfidenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        typeAndConfidence_ = value;
        onChanged();
      } else {
        typeAndConfidenceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public Builder setTypeAndConfidence(
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder builderForValue) {
      if (typeAndConfidenceBuilder_ == null) {
        typeAndConfidence_ = builderForValue.build();
        onChanged();
      } else {
        typeAndConfidenceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public Builder mergeTypeAndConfidence(org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence value) {
      if (typeAndConfidenceBuilder_ == null) {
        if (typeAndConfidence_ != null) {
          typeAndConfidence_ =
            org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.newBuilder(typeAndConfidence_).mergeFrom(value).buildPartial();
        } else {
          typeAndConfidence_ = value;
        }
        onChanged();
      } else {
        typeAndConfidenceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public Builder clearTypeAndConfidence() {
      if (typeAndConfidenceBuilder_ == null) {
        typeAndConfidence_ = null;
        onChanged();
      } else {
        typeAndConfidence_ = null;
        typeAndConfidenceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder getTypeAndConfidenceBuilder() {
      
      onChanged();
      return getTypeAndConfidenceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidenceOrBuilder getTypeAndConfidenceOrBuilder() {
      if (typeAndConfidenceBuilder_ != null) {
        return typeAndConfidenceBuilder_.getMessageOrBuilder();
      } else {
        return typeAndConfidence_ == null ?
            org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.getDefaultInstance() : typeAndConfidence_;
      }
    }
    /**
     * <pre>
     * Type and confidence.
     * </pre>
     *
     * <code>.sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence type_and_confidence = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidenceOrBuilder> 
        getTypeAndConfidenceFieldBuilder() {
      if (typeAndConfidenceBuilder_ == null) {
        typeAndConfidenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidence.Builder, org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit.TypeAndConfidenceOrBuilder>(
                getTypeAndConfidence(),
                getParentForChildren(),
                isClean());
        typeAndConfidence_ = null;
      }
      return typeAndConfidenceBuilder_;
    }

    private org.sensoris.types.spatial.PositionAndAccuracy positionAndAccuracy_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.spatial.PositionAndAccuracy, org.sensoris.types.spatial.PositionAndAccuracy.Builder, org.sensoris.types.spatial.PositionAndAccuracyOrBuilder> positionAndAccuracyBuilder_;
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public boolean hasPositionAndAccuracy() {
      return positionAndAccuracyBuilder_ != null || positionAndAccuracy_ != null;
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public org.sensoris.types.spatial.PositionAndAccuracy getPositionAndAccuracy() {
      if (positionAndAccuracyBuilder_ == null) {
        return positionAndAccuracy_ == null ? org.sensoris.types.spatial.PositionAndAccuracy.getDefaultInstance() : positionAndAccuracy_;
      } else {
        return positionAndAccuracyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public Builder setPositionAndAccuracy(org.sensoris.types.spatial.PositionAndAccuracy value) {
      if (positionAndAccuracyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        positionAndAccuracy_ = value;
        onChanged();
      } else {
        positionAndAccuracyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public Builder setPositionAndAccuracy(
        org.sensoris.types.spatial.PositionAndAccuracy.Builder builderForValue) {
      if (positionAndAccuracyBuilder_ == null) {
        positionAndAccuracy_ = builderForValue.build();
        onChanged();
      } else {
        positionAndAccuracyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public Builder mergePositionAndAccuracy(org.sensoris.types.spatial.PositionAndAccuracy value) {
      if (positionAndAccuracyBuilder_ == null) {
        if (positionAndAccuracy_ != null) {
          positionAndAccuracy_ =
            org.sensoris.types.spatial.PositionAndAccuracy.newBuilder(positionAndAccuracy_).mergeFrom(value).buildPartial();
        } else {
          positionAndAccuracy_ = value;
        }
        onChanged();
      } else {
        positionAndAccuracyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public Builder clearPositionAndAccuracy() {
      if (positionAndAccuracyBuilder_ == null) {
        positionAndAccuracy_ = null;
        onChanged();
      } else {
        positionAndAccuracy_ = null;
        positionAndAccuracyBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public org.sensoris.types.spatial.PositionAndAccuracy.Builder getPositionAndAccuracyBuilder() {
      
      onChanged();
      return getPositionAndAccuracyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    public org.sensoris.types.spatial.PositionAndAccuracyOrBuilder getPositionAndAccuracyOrBuilder() {
      if (positionAndAccuracyBuilder_ != null) {
        return positionAndAccuracyBuilder_.getMessageOrBuilder();
      } else {
        return positionAndAccuracy_ == null ?
            org.sensoris.types.spatial.PositionAndAccuracy.getDefaultInstance() : positionAndAccuracy_;
      }
    }
    /**
     * <pre>
     * Position and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy position_and_accuracy = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.spatial.PositionAndAccuracy, org.sensoris.types.spatial.PositionAndAccuracy.Builder, org.sensoris.types.spatial.PositionAndAccuracyOrBuilder> 
        getPositionAndAccuracyFieldBuilder() {
      if (positionAndAccuracyBuilder_ == null) {
        positionAndAccuracyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.spatial.PositionAndAccuracy, org.sensoris.types.spatial.PositionAndAccuracy.Builder, org.sensoris.types.spatial.PositionAndAccuracyOrBuilder>(
                getPositionAndAccuracy(),
                getParentForChildren(),
                isClean());
        positionAndAccuracy_ = null;
      }
      return positionAndAccuracyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit)
  }

  // @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.roadattribution.LaneBoundaryMergeSplit)
  private static final org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit();
  }

  public static org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LaneBoundaryMergeSplit>
      PARSER = new com.google.protobuf.AbstractParser<LaneBoundaryMergeSplit>() {
    @java.lang.Override
    public LaneBoundaryMergeSplit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LaneBoundaryMergeSplit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LaneBoundaryMergeSplit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LaneBoundaryMergeSplit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.sensoris.categories.roadattribution.LaneBoundaryMergeSplit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

