// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/types/base.proto

package org.sensoris.types.base;

public interface CountAndConfidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensoris.protobuf.types.base.CountAndConfidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Count.
   * &#64;unit 1
   * &#64;resolution 1
   * &#64;range [1, )
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  boolean hasCount();
  /**
   * <pre>
   * Count.
   * &#64;unit 1
   * &#64;resolution 1
   * &#64;range [1, )
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  com.google.protobuf.Int64Value getCount();
  /**
   * <pre>
   * Count.
   * &#64;unit 1
   * &#64;resolution 1
   * &#64;range [1, )
   * </pre>
   *
   * <code>.google.protobuf.Int64Value count = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getCountOrBuilder();

  /**
   * <pre>
   * Confidence of count.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
   */
  boolean hasConfidence();
  /**
   * <pre>
   * Confidence of count.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
   */
  org.sensoris.types.base.Confidence getConfidence();
  /**
   * <pre>
   * Confidence of count.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Confidence confidence = 2;</code>
   */
  org.sensoris.types.base.ConfidenceOrBuilder getConfidenceOrBuilder();
}
