// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/types/base.proto

package org.sensoris.types.base;

/**
 * <pre>
 * Int64 value that is either one int64 value and it's accuracy or provides statistics of several int64 values.
 * </pre>
 *
 * Protobuf type {@code sensoris.protobuf.types.base.Int64ValueAndAccuracy}
 */
public  final class Int64ValueAndAccuracy extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensoris.protobuf.types.base.Int64ValueAndAccuracy)
    Int64ValueAndAccuracyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Int64ValueAndAccuracy.newBuilder() to construct.
  private Int64ValueAndAccuracy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Int64ValueAndAccuracy() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Int64ValueAndAccuracy(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder subBuilder = null;
            if (valueOneofCase_ == 1) {
              subBuilder = ((org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_).toBuilder();
            }
            valueOneof_ =
                input.readMessage(org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_);
              valueOneof_ = subBuilder.buildPartial();
            }
            valueOneofCase_ = 1;
            break;
          }
          case 18: {
            org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.Builder subBuilder = null;
            if (valueOneofCase_ == 2) {
              subBuilder = ((org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_).toBuilder();
            }
            valueOneof_ =
                input.readMessage(org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_);
              valueOneof_ = subBuilder.buildPartial();
            }
            valueOneofCase_ = 2;
            break;
          }
          case 26: {
            org.sensoris.types.base.AbsoluteInt64Histogram.Builder subBuilder = null;
            if (valueOneofCase_ == 3) {
              subBuilder = ((org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_).toBuilder();
            }
            valueOneof_ =
                input.readMessage(org.sensoris.types.base.AbsoluteInt64Histogram.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_);
              valueOneof_ = subBuilder.buildPartial();
            }
            valueOneofCase_ = 3;
            break;
          }
          case 34: {
            org.sensoris.types.base.RelativeInt64Histogram.Builder subBuilder = null;
            if (valueOneofCase_ == 4) {
              subBuilder = ((org.sensoris.types.base.RelativeInt64Histogram) valueOneof_).toBuilder();
            }
            valueOneof_ =
                input.readMessage(org.sensoris.types.base.RelativeInt64Histogram.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.sensoris.types.base.RelativeInt64Histogram) valueOneof_);
              valueOneof_ = subBuilder.buildPartial();
            }
            valueOneofCase_ = 4;
            break;
          }
          case 42: {
            org.sensoris.types.base.Int64GaussianDistribution.Builder subBuilder = null;
            if (valueOneofCase_ == 5) {
              subBuilder = ((org.sensoris.types.base.Int64GaussianDistribution) valueOneof_).toBuilder();
            }
            valueOneof_ =
                input.readMessage(org.sensoris.types.base.Int64GaussianDistribution.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.sensoris.types.base.Int64GaussianDistribution) valueOneof_);
              valueOneof_ = subBuilder.buildPartial();
            }
            valueOneofCase_ = 5;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.sensoris.types.base.Int64ValueAndAccuracy.class, org.sensoris.types.base.Int64ValueAndAccuracy.Builder.class);
  }

  public interface ValueAndAccuracyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Value.
     * </pre>
     *
     * <code>int64 value = 1;</code>
     */
    long getValue();

    /**
     * <pre>
     * Accuracy.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value accuracy = 2;</code>
     */
    boolean hasAccuracy();
    /**
     * <pre>
     * Accuracy.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value accuracy = 2;</code>
     */
    com.google.protobuf.Int64Value getAccuracy();
    /**
     * <pre>
     * Accuracy.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value accuracy = 2;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getAccuracyOrBuilder();
  }
  /**
   * <pre>
   * Int64 value and accuracy.
   * </pre>
   *
   * Protobuf type {@code sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy}
   */
  public  static final class ValueAndAccuracy extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)
      ValueAndAccuracyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValueAndAccuracy.newBuilder() to construct.
    private ValueAndAccuracy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValueAndAccuracy() {
      value_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValueAndAccuracy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (accuracy_ != null) {
                subBuilder = accuracy_.toBuilder();
              }
              accuracy_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accuracy_);
                accuracy_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_ValueAndAccuracy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_ValueAndAccuracy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.class, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private long value_;
    /**
     * <pre>
     * Value.
     * </pre>
     *
     * <code>int64 value = 1;</code>
     */
    public long getValue() {
      return value_;
    }

    public static final int ACCURACY_FIELD_NUMBER = 2;
    private com.google.protobuf.Int64Value accuracy_;
    /**
     * <pre>
     * Accuracy.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value accuracy = 2;</code>
     */
    public boolean hasAccuracy() {
      return accuracy_ != null;
    }
    /**
     * <pre>
     * Accuracy.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value accuracy = 2;</code>
     */
    public com.google.protobuf.Int64Value getAccuracy() {
      return accuracy_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : accuracy_;
    }
    /**
     * <pre>
     * Accuracy.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value accuracy = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getAccuracyOrBuilder() {
      return getAccuracy();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0L) {
        output.writeInt64(1, value_);
      }
      if (accuracy_ != null) {
        output.writeMessage(2, getAccuracy());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value_);
      }
      if (accuracy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAccuracy());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)) {
        return super.equals(obj);
      }
      org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy other = (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      result = result && (hasAccuracy() == other.hasAccuracy());
      if (hasAccuracy()) {
        result = result && getAccuracy()
            .equals(other.getAccuracy());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      if (hasAccuracy()) {
        hash = (37 * hash) + ACCURACY_FIELD_NUMBER;
        hash = (53 * hash) + getAccuracy().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Int64 value and accuracy.
     * </pre>
     *
     * Protobuf type {@code sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_ValueAndAccuracy_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_ValueAndAccuracy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.class, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder.class);
      }

      // Construct using org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0L;

        if (accuracyBuilder_ == null) {
          accuracy_ = null;
        } else {
          accuracy_ = null;
          accuracyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_ValueAndAccuracy_descriptor;
      }

      public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy getDefaultInstanceForType() {
        return org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
      }

      public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy build() {
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy buildPartial() {
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy result = new org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy(this);
        result.value_ = value_;
        if (accuracyBuilder_ == null) {
          result.accuracy_ = accuracy_;
        } else {
          result.accuracy_ = accuracyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) {
          return mergeFrom((org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy other) {
        if (other == org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance()) return this;
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        if (other.hasAccuracy()) {
          mergeAccuracy(other.getAccuracy());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long value_ ;
      /**
       * <pre>
       * Value.
       * </pre>
       *
       * <code>int64 value = 1;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <pre>
       * Value.
       * </pre>
       *
       * <code>int64 value = 1;</code>
       */
      public Builder setValue(long value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Value.
       * </pre>
       *
       * <code>int64 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Int64Value accuracy_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> accuracyBuilder_;
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public boolean hasAccuracy() {
        return accuracyBuilder_ != null || accuracy_ != null;
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public com.google.protobuf.Int64Value getAccuracy() {
        if (accuracyBuilder_ == null) {
          return accuracy_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : accuracy_;
        } else {
          return accuracyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public Builder setAccuracy(com.google.protobuf.Int64Value value) {
        if (accuracyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accuracy_ = value;
          onChanged();
        } else {
          accuracyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public Builder setAccuracy(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (accuracyBuilder_ == null) {
          accuracy_ = builderForValue.build();
          onChanged();
        } else {
          accuracyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public Builder mergeAccuracy(com.google.protobuf.Int64Value value) {
        if (accuracyBuilder_ == null) {
          if (accuracy_ != null) {
            accuracy_ =
              com.google.protobuf.Int64Value.newBuilder(accuracy_).mergeFrom(value).buildPartial();
          } else {
            accuracy_ = value;
          }
          onChanged();
        } else {
          accuracyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public Builder clearAccuracy() {
        if (accuracyBuilder_ == null) {
          accuracy_ = null;
          onChanged();
        } else {
          accuracy_ = null;
          accuracyBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public com.google.protobuf.Int64Value.Builder getAccuracyBuilder() {
        
        onChanged();
        return getAccuracyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getAccuracyOrBuilder() {
        if (accuracyBuilder_ != null) {
          return accuracyBuilder_.getMessageOrBuilder();
        } else {
          return accuracy_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : accuracy_;
        }
      }
      /**
       * <pre>
       * Accuracy.
       * </pre>
       *
       * <code>.google.protobuf.Int64Value accuracy = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getAccuracyFieldBuilder() {
        if (accuracyBuilder_ == null) {
          accuracyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getAccuracy(),
                  getParentForChildren(),
                  isClean());
          accuracy_ = null;
        }
        return accuracyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)
    }

    // @@protoc_insertion_point(class_scope:sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy)
    private static final org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy();
    }

    public static org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValueAndAccuracy>
        PARSER = new com.google.protobuf.AbstractParser<ValueAndAccuracy>() {
      public ValueAndAccuracy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValueAndAccuracy(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValueAndAccuracy> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValueAndAccuracy> getParserForType() {
      return PARSER;
    }

    public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int valueOneofCase_ = 0;
  private java.lang.Object valueOneof_;
  public enum ValueOneofCase
      implements com.google.protobuf.Internal.EnumLite {
    VALUE_AND_ACCURACY(1),
    STATISTIC_MEASURE_AND_ACCURACY(2),
    ABSOLUTE_HISTOGRAM(3),
    RELATIVE_HISTOGRAM(4),
    GAUSSIAN_DISTRIBUTION(5),
    VALUEONEOF_NOT_SET(0);
    private final int value;
    private ValueOneofCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueOneofCase forNumber(int value) {
      switch (value) {
        case 1: return VALUE_AND_ACCURACY;
        case 2: return STATISTIC_MEASURE_AND_ACCURACY;
        case 3: return ABSOLUTE_HISTOGRAM;
        case 4: return RELATIVE_HISTOGRAM;
        case 5: return GAUSSIAN_DISTRIBUTION;
        case 0: return VALUEONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueOneofCase
  getValueOneofCase() {
    return ValueOneofCase.forNumber(
        valueOneofCase_);
  }

  public static final int VALUE_AND_ACCURACY_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Value and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
   */
  public boolean hasValueAndAccuracy() {
    return valueOneofCase_ == 1;
  }
  /**
   * <pre>
   * Value and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
   */
  public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy getValueAndAccuracy() {
    if (valueOneofCase_ == 1) {
       return (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_;
    }
    return org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
  }
  /**
   * <pre>
   * Value and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
   */
  public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracyOrBuilder getValueAndAccuracyOrBuilder() {
    if (valueOneofCase_ == 1) {
       return (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_;
    }
    return org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
  }

  public static final int STATISTIC_MEASURE_AND_ACCURACY_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Statistic measure and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
   */
  public boolean hasStatisticMeasureAndAccuracy() {
    return valueOneofCase_ == 2;
  }
  /**
   * <pre>
   * Statistic measure and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
   */
  public org.sensoris.types.base.Int64StatisticMeasureAndAccuracy getStatisticMeasureAndAccuracy() {
    if (valueOneofCase_ == 2) {
       return (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_;
    }
    return org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance();
  }
  /**
   * <pre>
   * Statistic measure and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
   */
  public org.sensoris.types.base.Int64StatisticMeasureAndAccuracyOrBuilder getStatisticMeasureAndAccuracyOrBuilder() {
    if (valueOneofCase_ == 2) {
       return (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_;
    }
    return org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance();
  }

  public static final int ABSOLUTE_HISTOGRAM_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Absolute histogram.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
   */
  public boolean hasAbsoluteHistogram() {
    return valueOneofCase_ == 3;
  }
  /**
   * <pre>
   * Absolute histogram.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
   */
  public org.sensoris.types.base.AbsoluteInt64Histogram getAbsoluteHistogram() {
    if (valueOneofCase_ == 3) {
       return (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_;
    }
    return org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance();
  }
  /**
   * <pre>
   * Absolute histogram.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
   */
  public org.sensoris.types.base.AbsoluteInt64HistogramOrBuilder getAbsoluteHistogramOrBuilder() {
    if (valueOneofCase_ == 3) {
       return (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_;
    }
    return org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance();
  }

  public static final int RELATIVE_HISTOGRAM_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Relative histogram.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
   */
  public boolean hasRelativeHistogram() {
    return valueOneofCase_ == 4;
  }
  /**
   * <pre>
   * Relative histogram.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
   */
  public org.sensoris.types.base.RelativeInt64Histogram getRelativeHistogram() {
    if (valueOneofCase_ == 4) {
       return (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_;
    }
    return org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance();
  }
  /**
   * <pre>
   * Relative histogram.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
   */
  public org.sensoris.types.base.RelativeInt64HistogramOrBuilder getRelativeHistogramOrBuilder() {
    if (valueOneofCase_ == 4) {
       return (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_;
    }
    return org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance();
  }

  public static final int GAUSSIAN_DISTRIBUTION_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Gaussian distribution.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
   */
  public boolean hasGaussianDistribution() {
    return valueOneofCase_ == 5;
  }
  /**
   * <pre>
   * Gaussian distribution.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
   */
  public org.sensoris.types.base.Int64GaussianDistribution getGaussianDistribution() {
    if (valueOneofCase_ == 5) {
       return (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_;
    }
    return org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance();
  }
  /**
   * <pre>
   * Gaussian distribution.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
   */
  public org.sensoris.types.base.Int64GaussianDistributionOrBuilder getGaussianDistributionOrBuilder() {
    if (valueOneofCase_ == 5) {
       return (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_;
    }
    return org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueOneofCase_ == 1) {
      output.writeMessage(1, (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_);
    }
    if (valueOneofCase_ == 2) {
      output.writeMessage(2, (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_);
    }
    if (valueOneofCase_ == 3) {
      output.writeMessage(3, (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_);
    }
    if (valueOneofCase_ == 4) {
      output.writeMessage(4, (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_);
    }
    if (valueOneofCase_ == 5) {
      output.writeMessage(5, (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valueOneofCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_);
    }
    if (valueOneofCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_);
    }
    if (valueOneofCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_);
    }
    if (valueOneofCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_);
    }
    if (valueOneofCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.sensoris.types.base.Int64ValueAndAccuracy)) {
      return super.equals(obj);
    }
    org.sensoris.types.base.Int64ValueAndAccuracy other = (org.sensoris.types.base.Int64ValueAndAccuracy) obj;

    boolean result = true;
    result = result && getValueOneofCase().equals(
        other.getValueOneofCase());
    if (!result) return false;
    switch (valueOneofCase_) {
      case 1:
        result = result && getValueAndAccuracy()
            .equals(other.getValueAndAccuracy());
        break;
      case 2:
        result = result && getStatisticMeasureAndAccuracy()
            .equals(other.getStatisticMeasureAndAccuracy());
        break;
      case 3:
        result = result && getAbsoluteHistogram()
            .equals(other.getAbsoluteHistogram());
        break;
      case 4:
        result = result && getRelativeHistogram()
            .equals(other.getRelativeHistogram());
        break;
      case 5:
        result = result && getGaussianDistribution()
            .equals(other.getGaussianDistribution());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valueOneofCase_) {
      case 1:
        hash = (37 * hash) + VALUE_AND_ACCURACY_FIELD_NUMBER;
        hash = (53 * hash) + getValueAndAccuracy().hashCode();
        break;
      case 2:
        hash = (37 * hash) + STATISTIC_MEASURE_AND_ACCURACY_FIELD_NUMBER;
        hash = (53 * hash) + getStatisticMeasureAndAccuracy().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ABSOLUTE_HISTOGRAM_FIELD_NUMBER;
        hash = (53 * hash) + getAbsoluteHistogram().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RELATIVE_HISTOGRAM_FIELD_NUMBER;
        hash = (53 * hash) + getRelativeHistogram().hashCode();
        break;
      case 5:
        hash = (37 * hash) + GAUSSIAN_DISTRIBUTION_FIELD_NUMBER;
        hash = (53 * hash) + getGaussianDistribution().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sensoris.types.base.Int64ValueAndAccuracy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.sensoris.types.base.Int64ValueAndAccuracy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Int64 value that is either one int64 value and it's accuracy or provides statistics of several int64 values.
   * </pre>
   *
   * Protobuf type {@code sensoris.protobuf.types.base.Int64ValueAndAccuracy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensoris.protobuf.types.base.Int64ValueAndAccuracy)
      org.sensoris.types.base.Int64ValueAndAccuracyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensoris.types.base.Int64ValueAndAccuracy.class, org.sensoris.types.base.Int64ValueAndAccuracy.Builder.class);
    }

    // Construct using org.sensoris.types.base.Int64ValueAndAccuracy.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      valueOneofCase_ = 0;
      valueOneof_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.sensoris.types.base.SensorisBaseTypes.internal_static_sensoris_protobuf_types_base_Int64ValueAndAccuracy_descriptor;
    }

    public org.sensoris.types.base.Int64ValueAndAccuracy getDefaultInstanceForType() {
      return org.sensoris.types.base.Int64ValueAndAccuracy.getDefaultInstance();
    }

    public org.sensoris.types.base.Int64ValueAndAccuracy build() {
      org.sensoris.types.base.Int64ValueAndAccuracy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.sensoris.types.base.Int64ValueAndAccuracy buildPartial() {
      org.sensoris.types.base.Int64ValueAndAccuracy result = new org.sensoris.types.base.Int64ValueAndAccuracy(this);
      if (valueOneofCase_ == 1) {
        if (valueAndAccuracyBuilder_ == null) {
          result.valueOneof_ = valueOneof_;
        } else {
          result.valueOneof_ = valueAndAccuracyBuilder_.build();
        }
      }
      if (valueOneofCase_ == 2) {
        if (statisticMeasureAndAccuracyBuilder_ == null) {
          result.valueOneof_ = valueOneof_;
        } else {
          result.valueOneof_ = statisticMeasureAndAccuracyBuilder_.build();
        }
      }
      if (valueOneofCase_ == 3) {
        if (absoluteHistogramBuilder_ == null) {
          result.valueOneof_ = valueOneof_;
        } else {
          result.valueOneof_ = absoluteHistogramBuilder_.build();
        }
      }
      if (valueOneofCase_ == 4) {
        if (relativeHistogramBuilder_ == null) {
          result.valueOneof_ = valueOneof_;
        } else {
          result.valueOneof_ = relativeHistogramBuilder_.build();
        }
      }
      if (valueOneofCase_ == 5) {
        if (gaussianDistributionBuilder_ == null) {
          result.valueOneof_ = valueOneof_;
        } else {
          result.valueOneof_ = gaussianDistributionBuilder_.build();
        }
      }
      result.valueOneofCase_ = valueOneofCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.sensoris.types.base.Int64ValueAndAccuracy) {
        return mergeFrom((org.sensoris.types.base.Int64ValueAndAccuracy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.sensoris.types.base.Int64ValueAndAccuracy other) {
      if (other == org.sensoris.types.base.Int64ValueAndAccuracy.getDefaultInstance()) return this;
      switch (other.getValueOneofCase()) {
        case VALUE_AND_ACCURACY: {
          mergeValueAndAccuracy(other.getValueAndAccuracy());
          break;
        }
        case STATISTIC_MEASURE_AND_ACCURACY: {
          mergeStatisticMeasureAndAccuracy(other.getStatisticMeasureAndAccuracy());
          break;
        }
        case ABSOLUTE_HISTOGRAM: {
          mergeAbsoluteHistogram(other.getAbsoluteHistogram());
          break;
        }
        case RELATIVE_HISTOGRAM: {
          mergeRelativeHistogram(other.getRelativeHistogram());
          break;
        }
        case GAUSSIAN_DISTRIBUTION: {
          mergeGaussianDistribution(other.getGaussianDistribution());
          break;
        }
        case VALUEONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.sensoris.types.base.Int64ValueAndAccuracy parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.sensoris.types.base.Int64ValueAndAccuracy) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueOneofCase_ = 0;
    private java.lang.Object valueOneof_;
    public ValueOneofCase
        getValueOneofCase() {
      return ValueOneofCase.forNumber(
          valueOneofCase_);
    }

    public Builder clearValueOneof() {
      valueOneofCase_ = 0;
      valueOneof_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracyOrBuilder> valueAndAccuracyBuilder_;
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public boolean hasValueAndAccuracy() {
      return valueOneofCase_ == 1;
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy getValueAndAccuracy() {
      if (valueAndAccuracyBuilder_ == null) {
        if (valueOneofCase_ == 1) {
          return (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_;
        }
        return org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
      } else {
        if (valueOneofCase_ == 1) {
          return valueAndAccuracyBuilder_.getMessage();
        }
        return org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public Builder setValueAndAccuracy(org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value) {
      if (valueAndAccuracyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueOneof_ = value;
        onChanged();
      } else {
        valueAndAccuracyBuilder_.setMessage(value);
      }
      valueOneofCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public Builder setValueAndAccuracy(
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder builderForValue) {
      if (valueAndAccuracyBuilder_ == null) {
        valueOneof_ = builderForValue.build();
        onChanged();
      } else {
        valueAndAccuracyBuilder_.setMessage(builderForValue.build());
      }
      valueOneofCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public Builder mergeValueAndAccuracy(org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value) {
      if (valueAndAccuracyBuilder_ == null) {
        if (valueOneofCase_ == 1 &&
            valueOneof_ != org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance()) {
          valueOneof_ = org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.newBuilder((org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          valueOneof_ = value;
        }
        onChanged();
      } else {
        if (valueOneofCase_ == 1) {
          valueAndAccuracyBuilder_.mergeFrom(value);
        }
        valueAndAccuracyBuilder_.setMessage(value);
      }
      valueOneofCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public Builder clearValueAndAccuracy() {
      if (valueAndAccuracyBuilder_ == null) {
        if (valueOneofCase_ == 1) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
      } else {
        if (valueOneofCase_ == 1) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
        }
        valueAndAccuracyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder getValueAndAccuracyBuilder() {
      return getValueAndAccuracyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    public org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracyOrBuilder getValueAndAccuracyOrBuilder() {
      if ((valueOneofCase_ == 1) && (valueAndAccuracyBuilder_ != null)) {
        return valueAndAccuracyBuilder_.getMessageOrBuilder();
      } else {
        if (valueOneofCase_ == 1) {
          return (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_;
        }
        return org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Value and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64ValueAndAccuracy.ValueAndAccuracy value_and_accuracy = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracyOrBuilder> 
        getValueAndAccuracyFieldBuilder() {
      if (valueAndAccuracyBuilder_ == null) {
        if (!(valueOneofCase_ == 1)) {
          valueOneof_ = org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.getDefaultInstance();
        }
        valueAndAccuracyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy.Builder, org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracyOrBuilder>(
                (org.sensoris.types.base.Int64ValueAndAccuracy.ValueAndAccuracy) valueOneof_,
                getParentForChildren(),
                isClean());
        valueOneof_ = null;
      }
      valueOneofCase_ = 1;
      onChanged();;
      return valueAndAccuracyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Int64StatisticMeasureAndAccuracy, org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.Builder, org.sensoris.types.base.Int64StatisticMeasureAndAccuracyOrBuilder> statisticMeasureAndAccuracyBuilder_;
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public boolean hasStatisticMeasureAndAccuracy() {
      return valueOneofCase_ == 2;
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public org.sensoris.types.base.Int64StatisticMeasureAndAccuracy getStatisticMeasureAndAccuracy() {
      if (statisticMeasureAndAccuracyBuilder_ == null) {
        if (valueOneofCase_ == 2) {
          return (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_;
        }
        return org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance();
      } else {
        if (valueOneofCase_ == 2) {
          return statisticMeasureAndAccuracyBuilder_.getMessage();
        }
        return org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public Builder setStatisticMeasureAndAccuracy(org.sensoris.types.base.Int64StatisticMeasureAndAccuracy value) {
      if (statisticMeasureAndAccuracyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueOneof_ = value;
        onChanged();
      } else {
        statisticMeasureAndAccuracyBuilder_.setMessage(value);
      }
      valueOneofCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public Builder setStatisticMeasureAndAccuracy(
        org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.Builder builderForValue) {
      if (statisticMeasureAndAccuracyBuilder_ == null) {
        valueOneof_ = builderForValue.build();
        onChanged();
      } else {
        statisticMeasureAndAccuracyBuilder_.setMessage(builderForValue.build());
      }
      valueOneofCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public Builder mergeStatisticMeasureAndAccuracy(org.sensoris.types.base.Int64StatisticMeasureAndAccuracy value) {
      if (statisticMeasureAndAccuracyBuilder_ == null) {
        if (valueOneofCase_ == 2 &&
            valueOneof_ != org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance()) {
          valueOneof_ = org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.newBuilder((org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          valueOneof_ = value;
        }
        onChanged();
      } else {
        if (valueOneofCase_ == 2) {
          statisticMeasureAndAccuracyBuilder_.mergeFrom(value);
        }
        statisticMeasureAndAccuracyBuilder_.setMessage(value);
      }
      valueOneofCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public Builder clearStatisticMeasureAndAccuracy() {
      if (statisticMeasureAndAccuracyBuilder_ == null) {
        if (valueOneofCase_ == 2) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
      } else {
        if (valueOneofCase_ == 2) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
        }
        statisticMeasureAndAccuracyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.Builder getStatisticMeasureAndAccuracyBuilder() {
      return getStatisticMeasureAndAccuracyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    public org.sensoris.types.base.Int64StatisticMeasureAndAccuracyOrBuilder getStatisticMeasureAndAccuracyOrBuilder() {
      if ((valueOneofCase_ == 2) && (statisticMeasureAndAccuracyBuilder_ != null)) {
        return statisticMeasureAndAccuracyBuilder_.getMessageOrBuilder();
      } else {
        if (valueOneofCase_ == 2) {
          return (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_;
        }
        return org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Statistic measure and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64StatisticMeasureAndAccuracy statistic_measure_and_accuracy = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Int64StatisticMeasureAndAccuracy, org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.Builder, org.sensoris.types.base.Int64StatisticMeasureAndAccuracyOrBuilder> 
        getStatisticMeasureAndAccuracyFieldBuilder() {
      if (statisticMeasureAndAccuracyBuilder_ == null) {
        if (!(valueOneofCase_ == 2)) {
          valueOneof_ = org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.getDefaultInstance();
        }
        statisticMeasureAndAccuracyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.Int64StatisticMeasureAndAccuracy, org.sensoris.types.base.Int64StatisticMeasureAndAccuracy.Builder, org.sensoris.types.base.Int64StatisticMeasureAndAccuracyOrBuilder>(
                (org.sensoris.types.base.Int64StatisticMeasureAndAccuracy) valueOneof_,
                getParentForChildren(),
                isClean());
        valueOneof_ = null;
      }
      valueOneofCase_ = 2;
      onChanged();;
      return statisticMeasureAndAccuracyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.AbsoluteInt64Histogram, org.sensoris.types.base.AbsoluteInt64Histogram.Builder, org.sensoris.types.base.AbsoluteInt64HistogramOrBuilder> absoluteHistogramBuilder_;
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public boolean hasAbsoluteHistogram() {
      return valueOneofCase_ == 3;
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public org.sensoris.types.base.AbsoluteInt64Histogram getAbsoluteHistogram() {
      if (absoluteHistogramBuilder_ == null) {
        if (valueOneofCase_ == 3) {
          return (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_;
        }
        return org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance();
      } else {
        if (valueOneofCase_ == 3) {
          return absoluteHistogramBuilder_.getMessage();
        }
        return org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public Builder setAbsoluteHistogram(org.sensoris.types.base.AbsoluteInt64Histogram value) {
      if (absoluteHistogramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueOneof_ = value;
        onChanged();
      } else {
        absoluteHistogramBuilder_.setMessage(value);
      }
      valueOneofCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public Builder setAbsoluteHistogram(
        org.sensoris.types.base.AbsoluteInt64Histogram.Builder builderForValue) {
      if (absoluteHistogramBuilder_ == null) {
        valueOneof_ = builderForValue.build();
        onChanged();
      } else {
        absoluteHistogramBuilder_.setMessage(builderForValue.build());
      }
      valueOneofCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public Builder mergeAbsoluteHistogram(org.sensoris.types.base.AbsoluteInt64Histogram value) {
      if (absoluteHistogramBuilder_ == null) {
        if (valueOneofCase_ == 3 &&
            valueOneof_ != org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance()) {
          valueOneof_ = org.sensoris.types.base.AbsoluteInt64Histogram.newBuilder((org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          valueOneof_ = value;
        }
        onChanged();
      } else {
        if (valueOneofCase_ == 3) {
          absoluteHistogramBuilder_.mergeFrom(value);
        }
        absoluteHistogramBuilder_.setMessage(value);
      }
      valueOneofCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public Builder clearAbsoluteHistogram() {
      if (absoluteHistogramBuilder_ == null) {
        if (valueOneofCase_ == 3) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
      } else {
        if (valueOneofCase_ == 3) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
        }
        absoluteHistogramBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public org.sensoris.types.base.AbsoluteInt64Histogram.Builder getAbsoluteHistogramBuilder() {
      return getAbsoluteHistogramFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    public org.sensoris.types.base.AbsoluteInt64HistogramOrBuilder getAbsoluteHistogramOrBuilder() {
      if ((valueOneofCase_ == 3) && (absoluteHistogramBuilder_ != null)) {
        return absoluteHistogramBuilder_.getMessageOrBuilder();
      } else {
        if (valueOneofCase_ == 3) {
          return (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_;
        }
        return org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Absolute histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.AbsoluteInt64Histogram absolute_histogram = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.AbsoluteInt64Histogram, org.sensoris.types.base.AbsoluteInt64Histogram.Builder, org.sensoris.types.base.AbsoluteInt64HistogramOrBuilder> 
        getAbsoluteHistogramFieldBuilder() {
      if (absoluteHistogramBuilder_ == null) {
        if (!(valueOneofCase_ == 3)) {
          valueOneof_ = org.sensoris.types.base.AbsoluteInt64Histogram.getDefaultInstance();
        }
        absoluteHistogramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.AbsoluteInt64Histogram, org.sensoris.types.base.AbsoluteInt64Histogram.Builder, org.sensoris.types.base.AbsoluteInt64HistogramOrBuilder>(
                (org.sensoris.types.base.AbsoluteInt64Histogram) valueOneof_,
                getParentForChildren(),
                isClean());
        valueOneof_ = null;
      }
      valueOneofCase_ = 3;
      onChanged();;
      return absoluteHistogramBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.RelativeInt64Histogram, org.sensoris.types.base.RelativeInt64Histogram.Builder, org.sensoris.types.base.RelativeInt64HistogramOrBuilder> relativeHistogramBuilder_;
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public boolean hasRelativeHistogram() {
      return valueOneofCase_ == 4;
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public org.sensoris.types.base.RelativeInt64Histogram getRelativeHistogram() {
      if (relativeHistogramBuilder_ == null) {
        if (valueOneofCase_ == 4) {
          return (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_;
        }
        return org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance();
      } else {
        if (valueOneofCase_ == 4) {
          return relativeHistogramBuilder_.getMessage();
        }
        return org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public Builder setRelativeHistogram(org.sensoris.types.base.RelativeInt64Histogram value) {
      if (relativeHistogramBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueOneof_ = value;
        onChanged();
      } else {
        relativeHistogramBuilder_.setMessage(value);
      }
      valueOneofCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public Builder setRelativeHistogram(
        org.sensoris.types.base.RelativeInt64Histogram.Builder builderForValue) {
      if (relativeHistogramBuilder_ == null) {
        valueOneof_ = builderForValue.build();
        onChanged();
      } else {
        relativeHistogramBuilder_.setMessage(builderForValue.build());
      }
      valueOneofCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public Builder mergeRelativeHistogram(org.sensoris.types.base.RelativeInt64Histogram value) {
      if (relativeHistogramBuilder_ == null) {
        if (valueOneofCase_ == 4 &&
            valueOneof_ != org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance()) {
          valueOneof_ = org.sensoris.types.base.RelativeInt64Histogram.newBuilder((org.sensoris.types.base.RelativeInt64Histogram) valueOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          valueOneof_ = value;
        }
        onChanged();
      } else {
        if (valueOneofCase_ == 4) {
          relativeHistogramBuilder_.mergeFrom(value);
        }
        relativeHistogramBuilder_.setMessage(value);
      }
      valueOneofCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public Builder clearRelativeHistogram() {
      if (relativeHistogramBuilder_ == null) {
        if (valueOneofCase_ == 4) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
      } else {
        if (valueOneofCase_ == 4) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
        }
        relativeHistogramBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public org.sensoris.types.base.RelativeInt64Histogram.Builder getRelativeHistogramBuilder() {
      return getRelativeHistogramFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    public org.sensoris.types.base.RelativeInt64HistogramOrBuilder getRelativeHistogramOrBuilder() {
      if ((valueOneofCase_ == 4) && (relativeHistogramBuilder_ != null)) {
        return relativeHistogramBuilder_.getMessageOrBuilder();
      } else {
        if (valueOneofCase_ == 4) {
          return (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_;
        }
        return org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Relative histogram.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.RelativeInt64Histogram relative_histogram = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.RelativeInt64Histogram, org.sensoris.types.base.RelativeInt64Histogram.Builder, org.sensoris.types.base.RelativeInt64HistogramOrBuilder> 
        getRelativeHistogramFieldBuilder() {
      if (relativeHistogramBuilder_ == null) {
        if (!(valueOneofCase_ == 4)) {
          valueOneof_ = org.sensoris.types.base.RelativeInt64Histogram.getDefaultInstance();
        }
        relativeHistogramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.RelativeInt64Histogram, org.sensoris.types.base.RelativeInt64Histogram.Builder, org.sensoris.types.base.RelativeInt64HistogramOrBuilder>(
                (org.sensoris.types.base.RelativeInt64Histogram) valueOneof_,
                getParentForChildren(),
                isClean());
        valueOneof_ = null;
      }
      valueOneofCase_ = 4;
      onChanged();;
      return relativeHistogramBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Int64GaussianDistribution, org.sensoris.types.base.Int64GaussianDistribution.Builder, org.sensoris.types.base.Int64GaussianDistributionOrBuilder> gaussianDistributionBuilder_;
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public boolean hasGaussianDistribution() {
      return valueOneofCase_ == 5;
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public org.sensoris.types.base.Int64GaussianDistribution getGaussianDistribution() {
      if (gaussianDistributionBuilder_ == null) {
        if (valueOneofCase_ == 5) {
          return (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_;
        }
        return org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance();
      } else {
        if (valueOneofCase_ == 5) {
          return gaussianDistributionBuilder_.getMessage();
        }
        return org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public Builder setGaussianDistribution(org.sensoris.types.base.Int64GaussianDistribution value) {
      if (gaussianDistributionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        valueOneof_ = value;
        onChanged();
      } else {
        gaussianDistributionBuilder_.setMessage(value);
      }
      valueOneofCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public Builder setGaussianDistribution(
        org.sensoris.types.base.Int64GaussianDistribution.Builder builderForValue) {
      if (gaussianDistributionBuilder_ == null) {
        valueOneof_ = builderForValue.build();
        onChanged();
      } else {
        gaussianDistributionBuilder_.setMessage(builderForValue.build());
      }
      valueOneofCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public Builder mergeGaussianDistribution(org.sensoris.types.base.Int64GaussianDistribution value) {
      if (gaussianDistributionBuilder_ == null) {
        if (valueOneofCase_ == 5 &&
            valueOneof_ != org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance()) {
          valueOneof_ = org.sensoris.types.base.Int64GaussianDistribution.newBuilder((org.sensoris.types.base.Int64GaussianDistribution) valueOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          valueOneof_ = value;
        }
        onChanged();
      } else {
        if (valueOneofCase_ == 5) {
          gaussianDistributionBuilder_.mergeFrom(value);
        }
        gaussianDistributionBuilder_.setMessage(value);
      }
      valueOneofCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public Builder clearGaussianDistribution() {
      if (gaussianDistributionBuilder_ == null) {
        if (valueOneofCase_ == 5) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
          onChanged();
        }
      } else {
        if (valueOneofCase_ == 5) {
          valueOneofCase_ = 0;
          valueOneof_ = null;
        }
        gaussianDistributionBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public org.sensoris.types.base.Int64GaussianDistribution.Builder getGaussianDistributionBuilder() {
      return getGaussianDistributionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    public org.sensoris.types.base.Int64GaussianDistributionOrBuilder getGaussianDistributionOrBuilder() {
      if ((valueOneofCase_ == 5) && (gaussianDistributionBuilder_ != null)) {
        return gaussianDistributionBuilder_.getMessageOrBuilder();
      } else {
        if (valueOneofCase_ == 5) {
          return (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_;
        }
        return org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Gaussian distribution.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Int64GaussianDistribution gaussian_distribution = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Int64GaussianDistribution, org.sensoris.types.base.Int64GaussianDistribution.Builder, org.sensoris.types.base.Int64GaussianDistributionOrBuilder> 
        getGaussianDistributionFieldBuilder() {
      if (gaussianDistributionBuilder_ == null) {
        if (!(valueOneofCase_ == 5)) {
          valueOneof_ = org.sensoris.types.base.Int64GaussianDistribution.getDefaultInstance();
        }
        gaussianDistributionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.Int64GaussianDistribution, org.sensoris.types.base.Int64GaussianDistribution.Builder, org.sensoris.types.base.Int64GaussianDistributionOrBuilder>(
                (org.sensoris.types.base.Int64GaussianDistribution) valueOneof_,
                getParentForChildren(),
                isClean());
        valueOneof_ = null;
      }
      valueOneofCase_ = 5;
      onChanged();;
      return gaussianDistributionBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensoris.protobuf.types.base.Int64ValueAndAccuracy)
  }

  // @@protoc_insertion_point(class_scope:sensoris.protobuf.types.base.Int64ValueAndAccuracy)
  private static final org.sensoris.types.base.Int64ValueAndAccuracy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.sensoris.types.base.Int64ValueAndAccuracy();
  }

  public static org.sensoris.types.base.Int64ValueAndAccuracy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Int64ValueAndAccuracy>
      PARSER = new com.google.protobuf.AbstractParser<Int64ValueAndAccuracy>() {
    public Int64ValueAndAccuracy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Int64ValueAndAccuracy(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Int64ValueAndAccuracy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Int64ValueAndAccuracy> getParserForType() {
    return PARSER;
  }

  public org.sensoris.types.base.Int64ValueAndAccuracy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

