// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensoris/protobuf/categories/localization.proto

package org.sensoris.categories.localization;

/**
 * <pre>
 * Vehicle odometry.
 * A vehicle odometry describes the translation and rotation from the vehicle position at envelope.timestamp to the vehicle position at end_timestamp.
 * The start and end vehicle position of a vehicle odometry can be set explicitly with event relations of type START and END.
 * &#64;relation 1 sensoris.protobuf.categories.localization.VehicleOdometry START 1 sensoris.protobuf.categories.localization.VehiclePositionAndOrientation
 * &#64;relation 1 sensoris.protobuf.categories.localization.VehicleOdometry END 1 sensoris.protobuf.categories.localization.VehiclePositionAndOrientation
 * </pre>
 *
 * Protobuf type {@code sensoris.protobuf.categories.localization.VehicleOdometry}
 */
public  final class VehicleOdometry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensoris.protobuf.categories.localization.VehicleOdometry)
    VehicleOdometryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VehicleOdometry.newBuilder() to construct.
  private VehicleOdometry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VehicleOdometry() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VehicleOdometry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.sensoris.types.base.EventEnvelope.Builder subBuilder = null;
            if (envelope_ != null) {
              subBuilder = envelope_.toBuilder();
            }
            envelope_ = input.readMessage(org.sensoris.types.base.EventEnvelope.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(envelope_);
              envelope_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.sensoris.types.base.Timestamp.Builder subBuilder = null;
            if (endTimestamp_ != null) {
              subBuilder = endTimestamp_.toBuilder();
            }
            endTimestamp_ = input.readMessage(org.sensoris.types.base.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endTimestamp_);
              endTimestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            org.sensoris.types.spatial.PositionAndAccuracy.Builder subBuilder = null;
            if (translationAndAccuracy_ != null) {
              subBuilder = translationAndAccuracy_.toBuilder();
            }
            translationAndAccuracy_ = input.readMessage(org.sensoris.types.spatial.PositionAndAccuracy.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(translationAndAccuracy_);
              translationAndAccuracy_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.sensoris.types.spatial.RotationAndAccuracy.Builder subBuilder = null;
            if (rotationAndAccuracy_ != null) {
              subBuilder = rotationAndAccuracy_.toBuilder();
            }
            rotationAndAccuracy_ = input.readMessage(org.sensoris.types.spatial.RotationAndAccuracy.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rotationAndAccuracy_);
              rotationAndAccuracy_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.sensoris.categories.localization.SensorisLocalizationCategory.internal_static_sensoris_protobuf_categories_localization_VehicleOdometry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.sensoris.categories.localization.SensorisLocalizationCategory.internal_static_sensoris_protobuf_categories_localization_VehicleOdometry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.sensoris.categories.localization.VehicleOdometry.class, org.sensoris.categories.localization.VehicleOdometry.Builder.class);
  }

  public static final int ENVELOPE_FIELD_NUMBER = 1;
  private org.sensoris.types.base.EventEnvelope envelope_;
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  public boolean hasEnvelope() {
    return envelope_ != null;
  }
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  public org.sensoris.types.base.EventEnvelope getEnvelope() {
    return envelope_ == null ? org.sensoris.types.base.EventEnvelope.getDefaultInstance() : envelope_;
  }
  /**
   * <pre>
   * Event envelope.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
   */
  public org.sensoris.types.base.EventEnvelopeOrBuilder getEnvelopeOrBuilder() {
    return getEnvelope();
  }

  public static final int END_TIMESTAMP_FIELD_NUMBER = 2;
  private org.sensoris.types.base.Timestamp endTimestamp_;
  /**
   * <pre>
   * End timestamp.
   * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
   */
  public boolean hasEndTimestamp() {
    return endTimestamp_ != null;
  }
  /**
   * <pre>
   * End timestamp.
   * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
   */
  public org.sensoris.types.base.Timestamp getEndTimestamp() {
    return endTimestamp_ == null ? org.sensoris.types.base.Timestamp.getDefaultInstance() : endTimestamp_;
  }
  /**
   * <pre>
   * End timestamp.
   * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
   */
  public org.sensoris.types.base.TimestampOrBuilder getEndTimestampOrBuilder() {
    return getEndTimestamp();
  }

  public static final int TRANSLATION_AND_ACCURACY_FIELD_NUMBER = 3;
  private org.sensoris.types.spatial.PositionAndAccuracy translationAndAccuracy_;
  /**
   * <pre>
   * Translation and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
   */
  public boolean hasTranslationAndAccuracy() {
    return translationAndAccuracy_ != null;
  }
  /**
   * <pre>
   * Translation and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
   */
  public org.sensoris.types.spatial.PositionAndAccuracy getTranslationAndAccuracy() {
    return translationAndAccuracy_ == null ? org.sensoris.types.spatial.PositionAndAccuracy.getDefaultInstance() : translationAndAccuracy_;
  }
  /**
   * <pre>
   * Translation and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
   */
  public org.sensoris.types.spatial.PositionAndAccuracyOrBuilder getTranslationAndAccuracyOrBuilder() {
    return getTranslationAndAccuracy();
  }

  public static final int ROTATION_AND_ACCURACY_FIELD_NUMBER = 4;
  private org.sensoris.types.spatial.RotationAndAccuracy rotationAndAccuracy_;
  /**
   * <pre>
   * Rotation and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
   */
  public boolean hasRotationAndAccuracy() {
    return rotationAndAccuracy_ != null;
  }
  /**
   * <pre>
   * Rotation and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
   */
  public org.sensoris.types.spatial.RotationAndAccuracy getRotationAndAccuracy() {
    return rotationAndAccuracy_ == null ? org.sensoris.types.spatial.RotationAndAccuracy.getDefaultInstance() : rotationAndAccuracy_;
  }
  /**
   * <pre>
   * Rotation and accuracy.
   * </pre>
   *
   * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
   */
  public org.sensoris.types.spatial.RotationAndAccuracyOrBuilder getRotationAndAccuracyOrBuilder() {
    return getRotationAndAccuracy();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (envelope_ != null) {
      output.writeMessage(1, getEnvelope());
    }
    if (endTimestamp_ != null) {
      output.writeMessage(2, getEndTimestamp());
    }
    if (translationAndAccuracy_ != null) {
      output.writeMessage(3, getTranslationAndAccuracy());
    }
    if (rotationAndAccuracy_ != null) {
      output.writeMessage(4, getRotationAndAccuracy());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (envelope_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEnvelope());
    }
    if (endTimestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndTimestamp());
    }
    if (translationAndAccuracy_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTranslationAndAccuracy());
    }
    if (rotationAndAccuracy_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRotationAndAccuracy());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.sensoris.categories.localization.VehicleOdometry)) {
      return super.equals(obj);
    }
    org.sensoris.categories.localization.VehicleOdometry other = (org.sensoris.categories.localization.VehicleOdometry) obj;

    boolean result = true;
    result = result && (hasEnvelope() == other.hasEnvelope());
    if (hasEnvelope()) {
      result = result && getEnvelope()
          .equals(other.getEnvelope());
    }
    result = result && (hasEndTimestamp() == other.hasEndTimestamp());
    if (hasEndTimestamp()) {
      result = result && getEndTimestamp()
          .equals(other.getEndTimestamp());
    }
    result = result && (hasTranslationAndAccuracy() == other.hasTranslationAndAccuracy());
    if (hasTranslationAndAccuracy()) {
      result = result && getTranslationAndAccuracy()
          .equals(other.getTranslationAndAccuracy());
    }
    result = result && (hasRotationAndAccuracy() == other.hasRotationAndAccuracy());
    if (hasRotationAndAccuracy()) {
      result = result && getRotationAndAccuracy()
          .equals(other.getRotationAndAccuracy());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEnvelope()) {
      hash = (37 * hash) + ENVELOPE_FIELD_NUMBER;
      hash = (53 * hash) + getEnvelope().hashCode();
    }
    if (hasEndTimestamp()) {
      hash = (37 * hash) + END_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getEndTimestamp().hashCode();
    }
    if (hasTranslationAndAccuracy()) {
      hash = (37 * hash) + TRANSLATION_AND_ACCURACY_FIELD_NUMBER;
      hash = (53 * hash) + getTranslationAndAccuracy().hashCode();
    }
    if (hasRotationAndAccuracy()) {
      hash = (37 * hash) + ROTATION_AND_ACCURACY_FIELD_NUMBER;
      hash = (53 * hash) + getRotationAndAccuracy().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.sensoris.categories.localization.VehicleOdometry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.sensoris.categories.localization.VehicleOdometry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Vehicle odometry.
   * A vehicle odometry describes the translation and rotation from the vehicle position at envelope.timestamp to the vehicle position at end_timestamp.
   * The start and end vehicle position of a vehicle odometry can be set explicitly with event relations of type START and END.
   * &#64;relation 1 sensoris.protobuf.categories.localization.VehicleOdometry START 1 sensoris.protobuf.categories.localization.VehiclePositionAndOrientation
   * &#64;relation 1 sensoris.protobuf.categories.localization.VehicleOdometry END 1 sensoris.protobuf.categories.localization.VehiclePositionAndOrientation
   * </pre>
   *
   * Protobuf type {@code sensoris.protobuf.categories.localization.VehicleOdometry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensoris.protobuf.categories.localization.VehicleOdometry)
      org.sensoris.categories.localization.VehicleOdometryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sensoris.categories.localization.SensorisLocalizationCategory.internal_static_sensoris_protobuf_categories_localization_VehicleOdometry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sensoris.categories.localization.SensorisLocalizationCategory.internal_static_sensoris_protobuf_categories_localization_VehicleOdometry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sensoris.categories.localization.VehicleOdometry.class, org.sensoris.categories.localization.VehicleOdometry.Builder.class);
    }

    // Construct using org.sensoris.categories.localization.VehicleOdometry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (envelopeBuilder_ == null) {
        envelope_ = null;
      } else {
        envelope_ = null;
        envelopeBuilder_ = null;
      }
      if (endTimestampBuilder_ == null) {
        endTimestamp_ = null;
      } else {
        endTimestamp_ = null;
        endTimestampBuilder_ = null;
      }
      if (translationAndAccuracyBuilder_ == null) {
        translationAndAccuracy_ = null;
      } else {
        translationAndAccuracy_ = null;
        translationAndAccuracyBuilder_ = null;
      }
      if (rotationAndAccuracyBuilder_ == null) {
        rotationAndAccuracy_ = null;
      } else {
        rotationAndAccuracy_ = null;
        rotationAndAccuracyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.sensoris.categories.localization.SensorisLocalizationCategory.internal_static_sensoris_protobuf_categories_localization_VehicleOdometry_descriptor;
    }

    @java.lang.Override
    public org.sensoris.categories.localization.VehicleOdometry getDefaultInstanceForType() {
      return org.sensoris.categories.localization.VehicleOdometry.getDefaultInstance();
    }

    @java.lang.Override
    public org.sensoris.categories.localization.VehicleOdometry build() {
      org.sensoris.categories.localization.VehicleOdometry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.sensoris.categories.localization.VehicleOdometry buildPartial() {
      org.sensoris.categories.localization.VehicleOdometry result = new org.sensoris.categories.localization.VehicleOdometry(this);
      if (envelopeBuilder_ == null) {
        result.envelope_ = envelope_;
      } else {
        result.envelope_ = envelopeBuilder_.build();
      }
      if (endTimestampBuilder_ == null) {
        result.endTimestamp_ = endTimestamp_;
      } else {
        result.endTimestamp_ = endTimestampBuilder_.build();
      }
      if (translationAndAccuracyBuilder_ == null) {
        result.translationAndAccuracy_ = translationAndAccuracy_;
      } else {
        result.translationAndAccuracy_ = translationAndAccuracyBuilder_.build();
      }
      if (rotationAndAccuracyBuilder_ == null) {
        result.rotationAndAccuracy_ = rotationAndAccuracy_;
      } else {
        result.rotationAndAccuracy_ = rotationAndAccuracyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.sensoris.categories.localization.VehicleOdometry) {
        return mergeFrom((org.sensoris.categories.localization.VehicleOdometry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.sensoris.categories.localization.VehicleOdometry other) {
      if (other == org.sensoris.categories.localization.VehicleOdometry.getDefaultInstance()) return this;
      if (other.hasEnvelope()) {
        mergeEnvelope(other.getEnvelope());
      }
      if (other.hasEndTimestamp()) {
        mergeEndTimestamp(other.getEndTimestamp());
      }
      if (other.hasTranslationAndAccuracy()) {
        mergeTranslationAndAccuracy(other.getTranslationAndAccuracy());
      }
      if (other.hasRotationAndAccuracy()) {
        mergeRotationAndAccuracy(other.getRotationAndAccuracy());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.sensoris.categories.localization.VehicleOdometry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.sensoris.categories.localization.VehicleOdometry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.sensoris.types.base.EventEnvelope envelope_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.EventEnvelope, org.sensoris.types.base.EventEnvelope.Builder, org.sensoris.types.base.EventEnvelopeOrBuilder> envelopeBuilder_;
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public boolean hasEnvelope() {
      return envelopeBuilder_ != null || envelope_ != null;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public org.sensoris.types.base.EventEnvelope getEnvelope() {
      if (envelopeBuilder_ == null) {
        return envelope_ == null ? org.sensoris.types.base.EventEnvelope.getDefaultInstance() : envelope_;
      } else {
        return envelopeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder setEnvelope(org.sensoris.types.base.EventEnvelope value) {
      if (envelopeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        envelope_ = value;
        onChanged();
      } else {
        envelopeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder setEnvelope(
        org.sensoris.types.base.EventEnvelope.Builder builderForValue) {
      if (envelopeBuilder_ == null) {
        envelope_ = builderForValue.build();
        onChanged();
      } else {
        envelopeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder mergeEnvelope(org.sensoris.types.base.EventEnvelope value) {
      if (envelopeBuilder_ == null) {
        if (envelope_ != null) {
          envelope_ =
            org.sensoris.types.base.EventEnvelope.newBuilder(envelope_).mergeFrom(value).buildPartial();
        } else {
          envelope_ = value;
        }
        onChanged();
      } else {
        envelopeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public Builder clearEnvelope() {
      if (envelopeBuilder_ == null) {
        envelope_ = null;
        onChanged();
      } else {
        envelope_ = null;
        envelopeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public org.sensoris.types.base.EventEnvelope.Builder getEnvelopeBuilder() {
      
      onChanged();
      return getEnvelopeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    public org.sensoris.types.base.EventEnvelopeOrBuilder getEnvelopeOrBuilder() {
      if (envelopeBuilder_ != null) {
        return envelopeBuilder_.getMessageOrBuilder();
      } else {
        return envelope_ == null ?
            org.sensoris.types.base.EventEnvelope.getDefaultInstance() : envelope_;
      }
    }
    /**
     * <pre>
     * Event envelope.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.EventEnvelope envelope = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.EventEnvelope, org.sensoris.types.base.EventEnvelope.Builder, org.sensoris.types.base.EventEnvelopeOrBuilder> 
        getEnvelopeFieldBuilder() {
      if (envelopeBuilder_ == null) {
        envelopeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.EventEnvelope, org.sensoris.types.base.EventEnvelope.Builder, org.sensoris.types.base.EventEnvelopeOrBuilder>(
                getEnvelope(),
                getParentForChildren(),
                isClean());
        envelope_ = null;
      }
      return envelopeBuilder_;
    }

    private org.sensoris.types.base.Timestamp endTimestamp_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Timestamp, org.sensoris.types.base.Timestamp.Builder, org.sensoris.types.base.TimestampOrBuilder> endTimestampBuilder_;
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public boolean hasEndTimestamp() {
      return endTimestampBuilder_ != null || endTimestamp_ != null;
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public org.sensoris.types.base.Timestamp getEndTimestamp() {
      if (endTimestampBuilder_ == null) {
        return endTimestamp_ == null ? org.sensoris.types.base.Timestamp.getDefaultInstance() : endTimestamp_;
      } else {
        return endTimestampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public Builder setEndTimestamp(org.sensoris.types.base.Timestamp value) {
      if (endTimestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endTimestamp_ = value;
        onChanged();
      } else {
        endTimestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public Builder setEndTimestamp(
        org.sensoris.types.base.Timestamp.Builder builderForValue) {
      if (endTimestampBuilder_ == null) {
        endTimestamp_ = builderForValue.build();
        onChanged();
      } else {
        endTimestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public Builder mergeEndTimestamp(org.sensoris.types.base.Timestamp value) {
      if (endTimestampBuilder_ == null) {
        if (endTimestamp_ != null) {
          endTimestamp_ =
            org.sensoris.types.base.Timestamp.newBuilder(endTimestamp_).mergeFrom(value).buildPartial();
        } else {
          endTimestamp_ = value;
        }
        onChanged();
      } else {
        endTimestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public Builder clearEndTimestamp() {
      if (endTimestampBuilder_ == null) {
        endTimestamp_ = null;
        onChanged();
      } else {
        endTimestamp_ = null;
        endTimestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public org.sensoris.types.base.Timestamp.Builder getEndTimestampBuilder() {
      
      onChanged();
      return getEndTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    public org.sensoris.types.base.TimestampOrBuilder getEndTimestampOrBuilder() {
      if (endTimestampBuilder_ != null) {
        return endTimestampBuilder_.getMessageOrBuilder();
      } else {
        return endTimestamp_ == null ?
            org.sensoris.types.base.Timestamp.getDefaultInstance() : endTimestamp_;
      }
    }
    /**
     * <pre>
     * End timestamp.
     * If the end timestamp and the event relation of type END are not set, then the end timestamp is the timestamp of the vehicle position directly following the envelope.timestamp.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.base.Timestamp end_timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.base.Timestamp, org.sensoris.types.base.Timestamp.Builder, org.sensoris.types.base.TimestampOrBuilder> 
        getEndTimestampFieldBuilder() {
      if (endTimestampBuilder_ == null) {
        endTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.base.Timestamp, org.sensoris.types.base.Timestamp.Builder, org.sensoris.types.base.TimestampOrBuilder>(
                getEndTimestamp(),
                getParentForChildren(),
                isClean());
        endTimestamp_ = null;
      }
      return endTimestampBuilder_;
    }

    private org.sensoris.types.spatial.PositionAndAccuracy translationAndAccuracy_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.spatial.PositionAndAccuracy, org.sensoris.types.spatial.PositionAndAccuracy.Builder, org.sensoris.types.spatial.PositionAndAccuracyOrBuilder> translationAndAccuracyBuilder_;
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public boolean hasTranslationAndAccuracy() {
      return translationAndAccuracyBuilder_ != null || translationAndAccuracy_ != null;
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public org.sensoris.types.spatial.PositionAndAccuracy getTranslationAndAccuracy() {
      if (translationAndAccuracyBuilder_ == null) {
        return translationAndAccuracy_ == null ? org.sensoris.types.spatial.PositionAndAccuracy.getDefaultInstance() : translationAndAccuracy_;
      } else {
        return translationAndAccuracyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public Builder setTranslationAndAccuracy(org.sensoris.types.spatial.PositionAndAccuracy value) {
      if (translationAndAccuracyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        translationAndAccuracy_ = value;
        onChanged();
      } else {
        translationAndAccuracyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public Builder setTranslationAndAccuracy(
        org.sensoris.types.spatial.PositionAndAccuracy.Builder builderForValue) {
      if (translationAndAccuracyBuilder_ == null) {
        translationAndAccuracy_ = builderForValue.build();
        onChanged();
      } else {
        translationAndAccuracyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public Builder mergeTranslationAndAccuracy(org.sensoris.types.spatial.PositionAndAccuracy value) {
      if (translationAndAccuracyBuilder_ == null) {
        if (translationAndAccuracy_ != null) {
          translationAndAccuracy_ =
            org.sensoris.types.spatial.PositionAndAccuracy.newBuilder(translationAndAccuracy_).mergeFrom(value).buildPartial();
        } else {
          translationAndAccuracy_ = value;
        }
        onChanged();
      } else {
        translationAndAccuracyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public Builder clearTranslationAndAccuracy() {
      if (translationAndAccuracyBuilder_ == null) {
        translationAndAccuracy_ = null;
        onChanged();
      } else {
        translationAndAccuracy_ = null;
        translationAndAccuracyBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public org.sensoris.types.spatial.PositionAndAccuracy.Builder getTranslationAndAccuracyBuilder() {
      
      onChanged();
      return getTranslationAndAccuracyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    public org.sensoris.types.spatial.PositionAndAccuracyOrBuilder getTranslationAndAccuracyOrBuilder() {
      if (translationAndAccuracyBuilder_ != null) {
        return translationAndAccuracyBuilder_.getMessageOrBuilder();
      } else {
        return translationAndAccuracy_ == null ?
            org.sensoris.types.spatial.PositionAndAccuracy.getDefaultInstance() : translationAndAccuracy_;
      }
    }
    /**
     * <pre>
     * Translation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.PositionAndAccuracy translation_and_accuracy = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.spatial.PositionAndAccuracy, org.sensoris.types.spatial.PositionAndAccuracy.Builder, org.sensoris.types.spatial.PositionAndAccuracyOrBuilder> 
        getTranslationAndAccuracyFieldBuilder() {
      if (translationAndAccuracyBuilder_ == null) {
        translationAndAccuracyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.spatial.PositionAndAccuracy, org.sensoris.types.spatial.PositionAndAccuracy.Builder, org.sensoris.types.spatial.PositionAndAccuracyOrBuilder>(
                getTranslationAndAccuracy(),
                getParentForChildren(),
                isClean());
        translationAndAccuracy_ = null;
      }
      return translationAndAccuracyBuilder_;
    }

    private org.sensoris.types.spatial.RotationAndAccuracy rotationAndAccuracy_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.spatial.RotationAndAccuracy, org.sensoris.types.spatial.RotationAndAccuracy.Builder, org.sensoris.types.spatial.RotationAndAccuracyOrBuilder> rotationAndAccuracyBuilder_;
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public boolean hasRotationAndAccuracy() {
      return rotationAndAccuracyBuilder_ != null || rotationAndAccuracy_ != null;
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public org.sensoris.types.spatial.RotationAndAccuracy getRotationAndAccuracy() {
      if (rotationAndAccuracyBuilder_ == null) {
        return rotationAndAccuracy_ == null ? org.sensoris.types.spatial.RotationAndAccuracy.getDefaultInstance() : rotationAndAccuracy_;
      } else {
        return rotationAndAccuracyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public Builder setRotationAndAccuracy(org.sensoris.types.spatial.RotationAndAccuracy value) {
      if (rotationAndAccuracyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rotationAndAccuracy_ = value;
        onChanged();
      } else {
        rotationAndAccuracyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public Builder setRotationAndAccuracy(
        org.sensoris.types.spatial.RotationAndAccuracy.Builder builderForValue) {
      if (rotationAndAccuracyBuilder_ == null) {
        rotationAndAccuracy_ = builderForValue.build();
        onChanged();
      } else {
        rotationAndAccuracyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public Builder mergeRotationAndAccuracy(org.sensoris.types.spatial.RotationAndAccuracy value) {
      if (rotationAndAccuracyBuilder_ == null) {
        if (rotationAndAccuracy_ != null) {
          rotationAndAccuracy_ =
            org.sensoris.types.spatial.RotationAndAccuracy.newBuilder(rotationAndAccuracy_).mergeFrom(value).buildPartial();
        } else {
          rotationAndAccuracy_ = value;
        }
        onChanged();
      } else {
        rotationAndAccuracyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public Builder clearRotationAndAccuracy() {
      if (rotationAndAccuracyBuilder_ == null) {
        rotationAndAccuracy_ = null;
        onChanged();
      } else {
        rotationAndAccuracy_ = null;
        rotationAndAccuracyBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public org.sensoris.types.spatial.RotationAndAccuracy.Builder getRotationAndAccuracyBuilder() {
      
      onChanged();
      return getRotationAndAccuracyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    public org.sensoris.types.spatial.RotationAndAccuracyOrBuilder getRotationAndAccuracyOrBuilder() {
      if (rotationAndAccuracyBuilder_ != null) {
        return rotationAndAccuracyBuilder_.getMessageOrBuilder();
      } else {
        return rotationAndAccuracy_ == null ?
            org.sensoris.types.spatial.RotationAndAccuracy.getDefaultInstance() : rotationAndAccuracy_;
      }
    }
    /**
     * <pre>
     * Rotation and accuracy.
     * </pre>
     *
     * <code>.sensoris.protobuf.types.spatial.RotationAndAccuracy rotation_and_accuracy = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.sensoris.types.spatial.RotationAndAccuracy, org.sensoris.types.spatial.RotationAndAccuracy.Builder, org.sensoris.types.spatial.RotationAndAccuracyOrBuilder> 
        getRotationAndAccuracyFieldBuilder() {
      if (rotationAndAccuracyBuilder_ == null) {
        rotationAndAccuracyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.sensoris.types.spatial.RotationAndAccuracy, org.sensoris.types.spatial.RotationAndAccuracy.Builder, org.sensoris.types.spatial.RotationAndAccuracyOrBuilder>(
                getRotationAndAccuracy(),
                getParentForChildren(),
                isClean());
        rotationAndAccuracy_ = null;
      }
      return rotationAndAccuracyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensoris.protobuf.categories.localization.VehicleOdometry)
  }

  // @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.localization.VehicleOdometry)
  private static final org.sensoris.categories.localization.VehicleOdometry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.sensoris.categories.localization.VehicleOdometry();
  }

  public static org.sensoris.categories.localization.VehicleOdometry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VehicleOdometry>
      PARSER = new com.google.protobuf.AbstractParser<VehicleOdometry>() {
    @java.lang.Override
    public VehicleOdometry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VehicleOdometry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VehicleOdometry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VehicleOdometry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.sensoris.categories.localization.VehicleOdometry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

